---
title: "Introduction to Statistical Learning"
subtitle: "Bachelor’s Degree Programme in Philosophy, International and Economic Studies, Ca' Foscari University of Venice."
author: "Aldo Solari"
institute: "Department of Economics, Ca' Foscari University of Venice"
lang: en
page-layout: full
execute:
  cache: false
format:
  html:
    html-math-method: katex
    echo: true
    callout-appearance: minimal
    theme: [simplex, template.css]
    toc: true
    toc-title: Table of contents
    embed-resources: false
    code-line-numbers: true
    smooth-scroll: true
    fig-dpi: 250
editor: 
  markdown: 
    wrap: 72
editor_options: 
  chunk_output_type: console
---

This is the website of the [Introduction to Statistical Learning]{.blue} course of the
Bachelor’s Degree Programme in Philosophy, International and Economic Studies, Ca' Foscari University of Venice.

## Teaching material

#### Required

- Gareth, J., D. Witten, T. Hastie, and R. Tibshirani. 2021. [*An Introduction to Statistical Learning with Applications in R*](https://www.statlearning.com/) (Second Edition). New York: Springer.

#### Optional

- Azzalini, A., and B. Scarpa. 2013. [*Data Analysis and Data Mining: an Introduction*](http://azzalini.stat.unipd.it/Book-DM/). Oxford University Press.

- Gareth, J., D. Witten, T. Hastie, R. Tibshirani and J. Taylor. 2023. [*An Introduction to Statistical Learning with Applications in Python*](https://www.statlearning.com/). New York: Springer.


### Slides and lecture notes

Slides and lecture notes are based on the textbook (both required and optional) and on the resources for ISL with R, 2nd Edition, available at [https://www.statlearning.com/resources-second-edition](https://www.statlearning.com/resources-second-edition)
.

The slides are meant to be used in HTML. However, if you *really* want
to convert the HTML slides into pdf files, you can [follow the
instruction of the quarto
documentation](https://quarto.org/docs/presentations/revealjs/presenting.html#print-to-pdf).

| Topic | Notes | Slides & Code |
|-------|-------|----------------|
| **Introduction** | [Unit A](slides/un_A.html) | [Slides Unit A](slides/un_A_slides.html) |
| **Lab 1** | [Lab 1](slides/un_lab1.html) | [Code Lab 1](code/un_lab1.R) |
| *Exercises* | [Exercises A - Conceptual](exe/exeC_A.html) | [Exercises A - Applied](exe/exeA_A.html) |
|---|---|---|
| **The Bias-Variance Trade-Off** | [Unit B](slides/un_B.html) | [Slides Unit B](slides/un_B_slides.html) |
| **Lab 2** | [Lab 2](slides/un_lab2.html) | [Code Lab 2](code/un_lab2.R) |
| *Exercises* | [Exercises B - Conceptual](exe/exeC_B.html) | [Exercises B - Applied](exe/exeA_B.html) |
|---|---|---|
| **Linear Regression** | [Unit C](slides/un_C.html) | [Slides Unit C](slides/un_C_slides.html) |
| **Lab 3** | [Lab 3](slides/un_lab3.html) | [Code Lab 3](code/un_lab3.R) |
| *Exercises* | [Exercises C - Conceptual](exe/exeC_C.html) | [Exercises C - Applied](exe/exeA_C.html) |
|---|---|---|
| **Tree-Based Methods** | [Unit D](slides/un_D.html) | [Slides Unit D](slides/un_D_slides.html) |
| **Lab 4** | [Lab 4](slides/un_lab4.html) | [Code Lab 4](code/un_lab4.R) |
| *Exercises* | [Exercises D - Conceptual](exe/exeC_D.html) | [Exercises D - Applied](exe/exeA_D.html) |
|---|---|---|
| **PCA and Matrix Completion** | [Unit E](slides/un_E.html) | [Slides Unit E](slides/un_E_slides.html) |
| **Lab 5** | [Lab 5](slides/un_lab5.html) | [Code Lab 5](code/un_lab5.R) |
| *Exercises* | [Exercises E - Conceptual](exe/exeC_E.html) | [Exercises E - Applied](exe/exeA_E.html) |


## Prerequisites

* Basic mathematical background (no advanced mathematics needed)

* Elementary knowledge of statistics is strongly recommended but not required (e.g., [Introduction to Probability for Economics](https://aldosolari.github.io/IPE/)) 

* Familiarity with linear regression is helpful but not required

* No detailed knowledge of matrix operations is required

* Previous exposure to a programming language (e.g., R or Python) is useful but not required

## Labs

The course is delivered in a lecture format, with selected sessions  devoted to programming activities (``*labs*''). Students must bring their own laptop to these sessions and have [R](https://cloud.r-project.org) and [RStudio](https://rstudio.com/products/rstudio/) installed.

## Exam

The exam consists of two parts: 

- **Data analysis project**, which aims to evaluate your ability to build predictive models. You must submit:

  - your predictions, together with the code used to reproduce them;  
  - a report (maximum 4 pages) describing your analysis.  

  The data analysis must be uploaded on the course Moodle page at least three days before the exam date and can be submitted only once per academic year.

- **Oral exam**, which may include a discussion of your data analysis and questions on the topics covered in class, including assigned exercises and programming.


<!-- ## Data Analysis Project -->

<!-- The dataset contains ratings from 10,000 users for 99 movies, along with dates of the ratings. The goal is to predict the ratings of 2,931 test users for the movie Miss Congeniality. -->

<!-- The data are provided in separate files for ratings, dates, and movie information. -->

<!-- - Train_ratings_all.dat: ratings for 99 movies (training set) -->
<!-- - Test_ratings_all.dat: ratings for 99 movies (test set) -->
<!-- - Train_dates_all.dat: dates of ratings (training set) -->
<!-- - Test_dates_all.dat: dates of ratings (test set) -->
<!-- - Train_y_rating.dat: ratings for Miss Congeniality (training set) -->
<!-- - Train_y_date.dat: dates of these ratings (training set) -->
<!-- - Test_y_date.dat: dates for Miss Congeniality (test set) -->
<!-- - Movie_titles.txt: movie titles and release dates -->

<!-- Ratings range from 1 to 5, with 0 indicating missing values. Dates are measured as days since January 1, 2017, with ‘0000’ indicating missing values. -->

<!-- The use of external data is not allowed, and only the libraries used in class may be used. Predictions are evaluated using RMSE on the test set. -->

<!-- Example of submission (to be uploaded in the dedicated section on the Moodle page, using the required format [studentID]_prediction.txt, [studentID]_code.pdf, and [studentID]_report.pdf): -->

<!-- [123456_prediction.txt](https://raw.githubusercontent.com/aldosolari/ISL/refs/heads/main/exam/123456_prediction.txt) -->

<!-- [123456_code.pdf](https://raw.githubusercontent.com/aldosolari/ISL/refs/heads/main/exam/123456_code.pdf) -->


## Office hours

Office hours are held on Fridays at 11:00 AM in office C2.111, San Giobbe Economic Campus. Please book an appointment in advance by email.

## Acknowledgments

The primary source of this website's content is the textbook [Gareth, Witten, Hastie and Tibshirani (2023)]{.orange}. A few pictures have been taken from the textbook; in these cases the original source is cited.

I am also grateful to [Tommaso Rigon](https://tommasorigon.github.io/) for the use of his Quarto template.

All the mistakes still present are mine.

------------------------------------------------------------------------
