<!DOCTYPE html>
<html lang="en"><head>
<script src="un_D_files/libs/clipboard/clipboard.min.js"></script>
<script src="un_D_files/libs/quarto-html/tabby.min.js"></script>
<script src="un_D_files/libs/quarto-html/popper.min.js"></script>
<script src="un_D_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="un_D_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="un_D_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="un_D_files/libs/quarto-html/quarto-syntax-highlighting-234273d1456647dabc34a594ac50e507.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <meta name="author" content="Aldo Solari">
  <title>Tree-based Methods</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="un_D_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="un_D_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="un_D_files/libs/revealjs/dist/theme/quarto-52f9c9ea99cef3131c4880afbe91edc6.css">
  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">
  <link href="un_D_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="un_D_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="un_D_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="un_D_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Tree-based Methods</h1>
  <p class="subtitle">Introduction to Statistical Learning - PISE</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
<span class="orange">Aldo Solari</span> 
</div>
        <p class="quarto-title-affiliation">
            <em>Ca’ Foscari University of Venice</em>
          </p>
    </div>
</div>

</section>
<section class="slide level2 center">

<p>This unit will cover the following <span class="orange">topics</span>:</p>
<ul>
<li>Regression Trees</li>
<li>Bagging</li>
<li>Random Forests</li>
<li>Boosting</li>
</ul>
</section>
<section id="regression-trees" class="slide level2 center">
<h2>Regression Trees</h2>
<ul>
<li><p>Tree-based methods involve <span class="orange">stratifying</span> or <span class="orange">segmenting</span> the predictor space into a number of simple regions.</p></li>
<li><p>Since the set of splitting rules used to segment the predictor space can be summarized in a tree, these types of approaches are known as <span class="orange">decision-tree</span> methods.</p></li>
</ul>
</section>
<section id="pros-and-cons" class="slide level2 center">
<h2>Pros and Cons</h2>
<ul>
<li><p>Tree-based methods are simple and useful for interpretation.</p></li>
<li><p>However they typically are not competitive with the best supervised learning approaches in terms of prediction accuracy.</p></li>
<li><p>Hence we also discuss <span class="blue">bagging</span>, <span class="blue">random forests</span>, and <span class="blue">boosting</span>. These methods grow multiple trees which are then combined to yield a single consensus prediction.</p></li>
<li><p>Combining a large number of trees can often result in dramatic improvements in prediction accuracy, at the expense of some loss interpretation.</p></li>
</ul>
</section>
<section id="baseball-salary-data-how-would-you-stratify-it" class="slide level2 center">
<h2>Baseball salary data: how would you stratify it?</h2>
<p>Salary is color-coded from low (blue, green) to high (yellow,red)</p>

<img data-src="un_D_files/figure-revealjs/unnamed-chunk-2-1.png" width="1000" class="r-stretch"></section>
<section id="decision-tree-for-these-data-isl-figure-8.1" class="slide level2 center">
<h2>Decision tree for these data (ISL Figure 8.1)</h2>

<img data-src="img/8_1.png" style="width:50.0%" class="r-stretch"></section>
<section id="details-of-previous-figure" class="slide level2 center">
<h2>Details of previous figure</h2>
<ul>
<li><p>For the Hitters data, a regression tree for predicting the log salary of a baseball player, based on the number of years that he has played in the major leagues and the number of hits that he made in the previous year.</p></li>
<li><p>At a given internal node, the label (of the form <span class="math inline">X_j &lt; t_k</span> ) indicates the left-hand branch emanating from that split, and the right-hand branch corresponds to <span class="math inline">X_j \geq t_k</span> . For instance, the split at the top of the tree results in two large branches. The left-hand branch corresponds to <code>Years</code>&lt;4.5, and the right-hand branch corresponds to <code>Years</code>&gt;=4.5.</p></li>
<li><p>The tree has two internal nodes and three terminal nodes, or leaves. The number in each leaf is the mean of the response for the observations that fall there.</p></li>
</ul>
</section>
<section id="results-isl-figure-8.2" class="slide level2 center">
<h2>Results (ISL Figure 8.2)</h2>
<p>Overall, the tree stratifies or segments the players into three regions of predictor space: <span class="math inline">R_1 =\{X |</span> <code>Years</code>&lt;4.5 <span class="math inline">\}</span>, <span class="math inline">R_2 =\{X |</span> <code>Years</code>&gt;=4.5, <code>Hits</code>&lt;117.5 <span class="math inline">\}</span>, and <span class="math inline">R_3 =\{X |</span> <code>Years</code>&gt;=4.5, <code>Hits</code>&gt;=117.5 <span class="math inline">\}</span>.</p>

<img data-src="img/8_2.png" style="width:80.0%" class="r-stretch"></section>
<section id="terminology-for-trees" class="slide level2 center">
<h2>Terminology for Trees</h2>
<ul>
<li><p>In keeping with the tree analogy, the regions <span class="math inline">R_1</span>, <span class="math inline">R_2</span>, and <span class="math inline">R_3</span> are known as <span class="orange">terminal nodes</span></p></li>
<li><p>Decision trees are typically drawn <span class="blue">upside down</span>, in the sense that the leaves are at the bottom of the tree.</p></li>
<li><p>The points along the tree where the predictor space is split are referred to as <span class="orange">internal nodes</span></p></li>
<li><p>In the hitters tree, the two internal nodes are indicated by the text <code>Years</code>&lt;4.5 and <code>Hits</code>&lt;117.5.</p></li>
</ul>
</section>
<section id="interpretation-of-results" class="slide level2 center">
<h2>Interpretation of Results</h2>
<ul>
<li><p><code>Years</code> is the most important factor in determining <code>Salary</code>, and players with less experience earn lower salaries than more experienced players.</p></li>
<li><p>Given that a player is less experienced, the number of <code>Hits</code> that he made in the previous year seems to play little role in his Salary.</p></li>
<li><p>But among players who have been in the major leagues for five or more years, the number of <code>Hits</code> made in the previous year does affect <code>Salary</code>, and players who made more <code>Hits</code> last year tend to have higher salaries.</p></li>
<li><p>Surely an over-simplification, but compared to a regression model, it is easy to display, interpret and explain</p></li>
</ul>
</section>
<section id="details-of-the-tree-building-process" class="slide level2 center">
<h2>Details of the tree-building process</h2>
<ol type="1">
<li><p>We divide the predictor space — that is, the set of possible values for <span class="math inline">X_1,X_2,\ldots,X_p</span> — into <span class="math inline">J</span> distinct and non-overlapping regions, <span class="math inline">R_1</span>,<span class="math inline">R_2</span>,…,<span class="math inline">R_J</span>.</p></li>
<li><p>For every observation that falls into the region <span class="math inline">R_j</span>, we make the same prediction, which is simply the mean of the response values for the training observations in <span class="math inline">R_j</span>.</p></li>
</ol>
</section>
<section id="more-details-of-the-tree-building-process" class="slide level2 center">
<h2>More details of the tree-building process</h2>
<ul>
<li><p>In theory, the regions could have any shape. However, we choose to divide the predictor space into high-dimensional rectangles, or boxes, for simplicity and for ease of interpretation of the resulting predictive model.</p></li>
<li><p>The goal is to find boxes <span class="math inline">R_1</span>,…,<span class="math inline">R_J</span> that minimize the RSS, given by <span class="math display">\sum_{j \in J} \sum_{i \in R_j}(y_i - \hat y_{R_j})^2</span> where <span class="math inline">y_{R_j}</span> is the mean response for the training observations within the <span class="math inline">j</span>th box.</p></li>
</ul>
</section>
<section id="more-details-of-the-tree-building-process-1" class="slide level2 center">
<h2>More details of the tree-building process</h2>
<ul>
<li><p>Unfortunately, it is computationally infeasible to consider every possible partition of the feature space into <span class="math inline">J</span> boxes.</p></li>
<li><p>For this reason, we take a <span class="orange">top-down</span>, <span class="orange">greedy</span> approach that is known as <span class="blue">recursive binary splitting</span>.</p></li>
<li><p>The approach is <span class="orange">top-down</span> because it begins at the top of the tree and then successively splits the predictor space; each split is indicated via two new branches further down on the tree.</p></li>
<li><p>It is <span class="orange">greedy</span> because at each step of the tree-building process, the best split is made at that particular step, rather than looking ahead and picking a split that will lead to a better tree in some future step.</p></li>
</ul>
</section>
<section id="details-continued" class="slide level2 center">
<h2>Details — Continued</h2>
<ul>
<li><p>We first select the predictor <span class="math inline">X_j</span> and the cutpoint <span class="math inline">s</span> such that splitting the predictor space into the regions <span class="math inline">\{X|X_j &lt;s \}</span> and <span class="math inline">\{X|X_j \geq s \}</span> leads to the greatest possible reduction in RSS.</p></li>
<li><p>Next, we repeat the process, looking for the best predictor and best cutpoint in order to split the data further so as to minimize the RSS within each of the resulting regions.</p></li>
<li><p>However, this time, instead of splitting the entire predictor space, we split one of the two previously identified regions. We now have three regions.</p></li>
<li><p>Again, we look to split one of these three regions further, so as to minimize the RSS. The process continues until a stopping criterion is reached; for instance, we may continue until no region contains more than five observations.</p></li>
</ul>
</section>
<section id="details-continued-1" class="slide level2 center">
<h2>Details — Continued</h2>
<ul>
<li><p>In greater detail, for any <span class="math inline">j</span> and <span class="math inline">s</span>, we define the pair of half-planes <span class="math display">
R_1(j, s) = \{X \mid X_j &lt; s\}, \quad R_2(j, s) = \{X \mid X_j \ge s\}.
</span></p></li>
<li><p>We then seek the pair <span class="math inline">(j,s)</span> that minimizes the residual sum of squares (RSS): <span class="math display">\sum_{i: x_i \in R_1(j,s)} (y_i - \hat{y}_{R_1})^2 \;+\;\sum_{i: x_i \in R_2(j,s)} (y_i - \hat{y}_{R_2})^2,</span> where <span class="math inline">\hat{y}_{R_1}</span> and <span class="math inline">\hat{y}_{R_2}</span> are the mean responses of the training observations in regions <span class="math inline">R_1(j,s)</span> and <span class="math inline">R_2(j,s)</span>, respectively.</p></li>
<li><p>In practice, this optimization is computationally efficient: for each predictor <span class="math inline">X_j</span>, we sort its values and evaluate candidate split points (typically between consecutive observations). As long as the number of predictors <span class="math inline">p</span> is not too large, the optimal split can be found quickly.</p></li>
</ul>
</section>
<section id="details-continued-2" class="slide level2 center">
<h2>Details — Continued</h2>
<ul>
<li><p>After obtaining the first split, we have two regions <span class="math inline">R_1</span> and <span class="math inline">R_2</span>. Instead of splitting the entire predictor space again, we consider splitting one of these regions further.</p></li>
<li><p>For any region <span class="math inline">R \in \{R_1, R_2\}</span>, predictor <span class="math inline">X_j</span>, and split point <span class="math inline">s</span>, we define: <span class="math display">
R_{L}(j, s; R) = \{X \in R \mid X_j &lt; s\}, \quad
R_{R}(j, s; R) = \{X \in R \mid X_j \ge s\}.
</span></p></li>
<li><p>We then seek the region <span class="math inline">R</span>, predictor <span class="math inline">j</span>, and split point <span class="math inline">s</span> that minimize the total residual sum of squares (RSS) after the second split: <span class="math display">
\sum_{i: x_i \in R_{L}(j,s;R)} (y_i - \hat{y}_{L})^2
\;+\;
\sum_{i: x_i \in R_{R}(j,s;R)} (y_i - \hat{y}_{R})^2
\;+\;
\sum_{i: x_i \in R^{c}} (y_i - \hat{y}_{R^{c}})^2,
</span> where <span class="math inline">R^{c}</span> denotes the region not being split, and <span class="math inline">\hat{y}_{L}</span>, <span class="math inline">\hat{y}_{R}</span>, and <span class="math inline">\hat{y}_{R^{c}}</span> are the mean responses in the corresponding regions.</p></li>
<li><p>Etc.</p></li>
</ul>
</section>
<section id="predictions" class="slide level2 center">
<h2>Predictions</h2>
<ul>
<li><p>We predict the response for a given test observation using the mean of the training observations in the region to which that test observation belongs.</p></li>
<li><p>A five-region example of this approach is shown in the next slide.</p></li>
</ul>
</section>
<section id="isl-figure-8.3" class="slide level2 center">
<h2>ISL Figure 8.3</h2>

<img data-src="img/8_3.png" style="width:80.0%" class="r-stretch"></section>
<section id="details-of-previous-figure-1" class="slide level2 center">
<h2>Details of previous figure</h2>
<ul>
<li><p><span class="orange">Top Left</span>: A partition of two-dimensional feature space that could not result from recursive binary splitting.</p></li>
<li><p><span class="orange">Top Right</span>: The output of recursive binary splitting on a two-dimensional example.</p></li>
<li><p><span class="orange">Bottom Left</span>: A tree corresponding to the partition in the top right panel.</p></li>
<li><p><span class="orange">Bottom Right</span>: A perspective plot of the prediction surface corresponding to that tree.</p></li>
</ul>
</section>
<section id="baseball-example" class="slide level2 center">
<h2>Baseball example</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   split      RSS
1    1.5 50776870
2    2.5 50776870
3    3.5 50776870
4    4.5 51352898
5    5.5 51352898
6    6.5 51352898
7    7.5 51352898
8    8.5 51352898
9    9.5 51352898
10  10.5 51352898
11  11.5 51352898
12  12.5 51352898
13  13.5 51352898
14  14.5 51352898
15  15.5 51352898
16  16.5 51352898
17  17.5 51352898
18  18.5 51352898
19  19.5 51352898
20  22.0 51352898</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   split      RSS
1    1.5 50607227
2    2.5 47908697
3    3.5 43120878
4    4.5 40162624
5    5.5 42045385
6    6.5 44051490
7    7.5 45812134
8    8.5 46567073
9    9.5 48443416
10  10.5 49171341
11  11.5 50175619
12  12.5 50023227
13  13.5 52385589
14  14.5 53194949
15  15.5 53230954
16  16.5 53232002
17  17.5 53277580
18  18.5 53308319
19  19.5 53309336
20  22.0 53273110</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Best split on Years = 4.5 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Minimum RSS = 40162624 </code></pre>
</div>
</div>
</section>
<section id="baseball-example-continued" class="slide level2 center">
<h2>Baseball example continued</h2>

<img data-src="un_D_files/figure-revealjs/unnamed-chunk-4-1.png" width="1000" class="r-stretch"></section>
<section id="baseball-example-continued-1" class="slide level2 center">
<h2>Baseball example continued</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Left region (Years &lt; 4.50): n = 90, mean Salary = 225.83</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Right region (Years &gt;= 4.50): n = 173, mean Salary = 697.25</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Interpretation:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>The left region contains 90 players with Years &lt; 4.5 and average Salary = 225.83 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>The right region contains 173 players with Years &gt;= 4.5 and average Salary = 697.25 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>These means are the predicted Salary values assigned to each region after the split.</code></pre>
</div>
</div>
</section>
<section id="baseball-example-continued-2" class="slide level2 center">
<h2>Baseball example continued</h2>

<img data-src="un_D_files/figure-revealjs/unnamed-chunk-6-1.png" width="1000" class="r-stretch"></section>
<section id="baseball-example-continued-3" class="slide level2 center">
<h2>Baseball example continued</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    region variable split region_RSS total_RSS
1     Left    Years   1.5    6647525  40040977
2     Left    Years   2.5    6669573  40063025
3     Left    Years   3.5    6375188  39768640
4     Left     Hits   2.5    3112837  36506290
5     Left     Hits  15.5    3323857  36717310
6     Left     Hits  32.0    4509594  37903047
7     Left     Hits  38.0    5257158  38650610
8     Left     Hits  39.5    5694084  39087536
9     Left     Hits  40.5    5968610  39362062
10    Left     Hits  42.0    6310631  39704084
11    Left     Hits  44.5    6402938  39796390
12    Left     Hits  48.5    6452966  39846418
13    Left     Hits  52.0    6529673  39923125
14    Left     Hits  53.5    6644674  40038126
15    Left     Hits  55.0    6706979  40100431
16    Left     Hits  56.5    6727691  40121143
17    Left     Hits  57.5    6737680  40131132
18    Left     Hits  59.0    6741962  40135414
19    Left     Hits  62.0    6758007  40151460
20    Left     Hits  65.0    6764512  40157964
21    Left     Hits  67.0    6767916  40161368
22    Left     Hits  68.5    6769170  40162622
23    Left     Hits  69.5    6769058  40162510
24    Left     Hits  70.5    6768913  40162366
25    Left     Hits  72.0    6769016  40162468
26    Left     Hits  74.0    6764833  40158285
27    Left     Hits  75.5    6762067  40155519
28    Left     Hits  77.0    6760044  40153496
29    Left     Hits  79.5    6752605  40146057
30    Left     Hits  81.5    6743400  40136852
31    Left     Hits  84.0    6735075  40128527
32    Left     Hits  86.5    6728025  40121477
33    Left     Hits  89.0    6715910  40109362
34    Left     Hits  91.5    6705865  40099317
35    Left     Hits  92.5    6682458  40075910
36    Left     Hits  94.5    6672920  40066372
37    Left     Hits  96.5    6669400  40062852
38    Left     Hits  98.0    6667129  40060581
39    Left     Hits 100.0    6647325  40040777
40    Left     Hits 102.0    6621545  40014997
41    Left     Hits 105.5    6576283  39969735
42    Left     Hits 108.5    6548230  39941682
43    Left     Hits 110.5    6522835  39916288
44    Left     Hits 112.5    6500018  39893470
45    Left     Hits 113.5    6534922  39928375
46    Left     Hits 114.5    6582306  39975758
47    Left     Hits 116.0    6593473  39986926
48    Left     Hits 117.5    6569638  39963091
49    Left     Hits 119.0    6551041  39944493
50    Left     Hits 121.0    6520809  39914261
51    Left     Hits 122.5    6543468  39936920
52    Left     Hits 125.0    6709530  40102982
53    Left     Hits 128.5    6705042  40098494
54    Left     Hits 131.0    6731272  40124724
55    Left     Hits 133.5    6728967  40122420
56    Left     Hits 136.0    6721806  40115258
57    Left     Hits 137.5    6714021  40107473
58    Left     Hits 138.5    6688320  40081772
59    Left     Hits 139.5    6673531  40066983
60    Left     Hits 141.0    6663826  40057278
61    Left     Hits 143.0    6633094  40026546
62    Left     Hits 144.5    6610323  40003775
63    Left     Hits 147.0    6580704  39974156
64    Left     Hits 150.5    6540519  39933972
65    Left     Hits 154.5    6482991  39876444
66    Left     Hits 159.0    6600636  39994088
67    Left     Hits 162.0    6691264  40084716
68    Left     Hits 165.0    6759757  40153210
69    Left     Hits 169.5    6755729  40149181
70    Left     Hits 186.0    6740668  40134120
71    Left     Hits 206.5    6733710  40127162
72    Left     Hits 218.0    6749586  40143038
73   Right    Years   5.5   32893956  39663128
74   Right    Years   6.5   32615377  39384548
75   Right    Years   7.5   32692681  39461852
76   Right    Years   8.5   32672489  39441661
77   Right    Years   9.5   33042422  39811593
78   Right    Years  10.5   33044862  39814033
79   Right    Years  11.5   33209508  39978679
80   Right    Years  12.5   32994115  39763286
81   Right    Years  13.5   33384126  40153297
82   Right    Years  14.5   33133697  39902869
83   Right    Years  15.5   33216785  39985956
84   Right    Years  16.5   33284512  40053683
85   Right    Years  17.5   33308559  40077730
86   Right    Years  18.5   33207905  39977076
87   Right    Years  19.5   33248258  40017429
88   Right    Years  22.0   33390653  40159824
89   Right     Hits  35.5   33101664  39870835
90   Right     Hits  40.0   32650379  39419550
91   Right     Hits  41.5   32449185  39218357
92   Right     Hits  42.5   32744667  39513838
93   Right     Hits  43.5   32361303  39130475
94   Right     Hits  45.0   32171721  38940893
95   Right     Hits  46.5   31900293  38669464
96   Right     Hits  48.0   31620013  38389185
97   Right     Hits  50.5   31316310  38085482
98   Right     Hits  52.5   31163639  37932811
99   Right     Hits  53.5   31137864  37907035
100  Right     Hits  54.5   30948156  37717327
101  Right     Hits  55.5   31473000  38242172
102  Right     Hits  56.5   30997604  37766775
103  Right     Hits  58.5   30770414  37539585
104  Right     Hits  60.5   30864763  37633934
105  Right     Hits  62.0   30627002  37396173
106  Right     Hits  64.0   30461979  37231150
107  Right     Hits  65.5   30517746  37286917
108  Right     Hits  67.0   30284267  37053438
109  Right     Hits  69.0   29551514  36320686
110  Right     Hits  71.0   29171762  35940934
111  Right     Hits  72.5   28817603  35586775
112  Right     Hits  73.5   28910206  35679377
113  Right     Hits  75.0   29019835  35789007
114  Right     Hits  76.5   28392178  35161349
115  Right     Hits  77.5   28084135  34853307
116  Right     Hits  79.0   27845378  34614549
117  Right     Hits  80.5   27914297  34683468
118  Right     Hits  81.5   27493061  34262232
119  Right     Hits  82.5   27335771  34104943
120  Right     Hits  83.5   27017425  33786596
121  Right     Hits  84.5   26968334  33737505
122  Right     Hits  87.5   26468543  33237714
123  Right     Hits  90.5   26311752  33080924
124  Right     Hits  91.5   26467453  33236625
125  Right     Hits  92.5   26560768  33329940
126  Right     Hits  93.5   26315163  33084334
127  Right     Hits  94.5   26360456  33129627
128  Right     Hits  95.5   25895528  32664700
129  Right     Hits  98.5   25652587  32421758
130  Right     Hits 101.5   25688607  32457779
131  Right     Hits 102.5   24951695  31720867
132  Right     Hits 103.5   24090300  30859472
133  Right     Hits 105.0   24154209  30923381
134  Right     Hits 108.0   24307350  31076522
135  Right     Hits 111.0   24106495  30875666
136  Right     Hits 112.5   24157798  30926969
137  Right     Hits 114.5   23941950  30711121
138  Right     Hits 116.5   23845691  30614862
139  Right     Hits 117.5   23267845  30037016
140  Right     Hits 118.5   23832964  30602135
141  Right     Hits 119.5   24001373  30770545
142  Right     Hits 121.0   23889699  30658871
143  Right     Hits 122.5   23712718  30481889
144  Right     Hits 123.5   24216204  30985375
145  Right     Hits 124.5   24051149  30820320
146  Right     Hits 125.5   25140680  31909851
147  Right     Hits 126.5   24835707  31604878
148  Right     Hits 127.5   25201312  31970484
149  Right     Hits 128.5   25729885  32499056
150  Right     Hits 130.0   25734520  32503691
151  Right     Hits 131.5   25673613  32442785
152  Right     Hits 132.5   25893991  32663162
153  Right     Hits 134.0   25907841  32677012
154  Right     Hits 135.5   25899090  32668261
155  Right     Hits 136.5   26033456  32802628
156  Right     Hits 138.0   26286199  33055370
157  Right     Hits 140.0   26107483  32876654
158  Right     Hits 141.5   25738373  32507544
159  Right     Hits 143.0   26335514  33104685
160  Right     Hits 144.5   27468898  34238069
161  Right     Hits 145.5   27224532  33993704
162  Right     Hits 146.5   27240990  34010161
163  Right     Hits 147.5   27526855  34296026
164  Right     Hits 148.5   28317566  35086737
165  Right     Hits 149.5   28303490  35072661
166  Right     Hits 150.5   28459678  35228850
167  Right     Hits 151.5   29714011  36483182
168  Right     Hits 153.0   29690222  36459393
169  Right     Hits 155.5   29480135  36249307
170  Right     Hits 157.5   29172788  35941960
171  Right     Hits 158.5   28999584  35768756
172  Right     Hits 159.5   28578626  35347797
173  Right     Hits 161.5   29300567  36069738
174  Right     Hits 165.5   30231961  37001133
175  Right     Hits 168.5   30274098  37043270
176  Right     Hits 169.5   29953537  36722709
177  Right     Hits 170.5   30388752  37157924
178  Right     Hits 172.5   31210593  37979764
179  Right     Hits 175.5   31158831  37928003
180  Right     Hits 177.5   31562507  38331678
181  Right     Hits 178.5   31430986  38200158
182  Right     Hits 181.0   31101254  37870425
183  Right     Hits 183.5   30919695  37688866
184  Right     Hits 185.0   30495666  37264837
185  Right     Hits 192.0   30888469  37657640
186  Right     Hits 199.0   31107929  37877101
187  Right     Hits 203.5   32725125  39494296
188  Right     Hits 208.5   33220880  39990051
189  Right     Hits 210.5   32511386  39280557
190  Right     Hits 224.5   31751306  38520478</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Best second split:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Region = Right </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Variable = Hits </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Split = 117.5 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Total RSS = 30037016 </code></pre>
</div>
</div>
</section>
<section id="pruning-a-tree" class="slide level2 center">
<h2>Pruning a tree</h2>
<ul>
<li><p>The process described above may produce good predictions on the training set, but is likely to <span class="blue">overfit</span> the data, leading to poor test set performance. <span class="blue">Why?</span></p></li>
<li><p>A smaller tree with fewer splits (that is, fewer regions <span class="math inline">R_1,\ldots,R_J</span> ) might lead to lower variance and better interpretation at the cost of a little bias.</p></li>
<li><p>One possible alternative to the process described above is to grow the tree only so long as the decrease in the RSS due to each split exceeds some (high) threshold.</p></li>
<li><p>This strategy will result in smaller trees, but is too <span class="blue">short-sighted</span>: a seemingly worthless split early on in the tree might be followed by a very good split — that is, a split that leads to a large reduction in RSS later on.</p></li>
</ul>
</section>
<section id="pruning-a-tree---continued" class="slide level2 center">
<h2>Pruning a tree - continued</h2>
<ul>
<li><p>A better strategy is to grow a very large tree <span class="math inline">T_0</span>, and then <span class="orange">prune</span> it back in order to obtain a <span class="orange">subtree</span></p></li>
<li><p><span class="orange">Cost complexity pruning</span> — also known as <span class="orange">weakest link pruning</span> — is used to do this</p></li>
<li><p>we consider a sequence of trees indexed by a nonnegative tuning parameter <span class="math inline">\alpha</span>. For each value of <span class="math inline">\alpha</span> there corresponds a subtree <span class="math inline">T \subset T_0</span> such that <span class="math display">\sum_{m=1}^{|T|} \sum_{i: x_i \in R_m}(y_i - \hat{y}_{R_m})^2 + \alpha |T|</span> is as small as possible. Here <span class="math inline">|T|</span> indicates the number of terminal nodes of the tree <span class="math inline">T</span>, <span class="math inline">R_m</span> is the rectangle (i.e.&nbsp;the subset of predictor space) corresponding to the <span class="math inline">m</span>th terminal node, and <span class="math inline">\hat{y}_{R_m}</span> is the mean of the training observations in <span class="math inline">R_m</span>.</p></li>
</ul>
</section>
<section id="choosing-the-best-subtree" class="slide level2 center">
<h2>Choosing the best subtree</h2>
<ul>
<li><p>The tuning parameter <span class="math inline">\alpha</span> controls a trade-oﬀ between the subtree’s complexity and its fit to the training data.</p></li>
<li><p>We select an optimal value <span class="math inline">\hat \alpha</span> using cross-validation.</p></li>
<li><p>We then return to the full data set and obtain the subtree corresponding to <span class="math inline">\hat \alpha</span></p></li>
</ul>
</section>
<section id="summary-tree-algorithm" class="slide level2 center">
<h2>Summary: tree algorithm</h2>
<ol type="1">
<li><p>Use recursive binary splitting to grow a large tree on the training data, stopping only when each terminal node has fewer than some minimum number of observations.</p></li>
<li><p>Apply cost complexity pruning to the large tree in order to obtain a sequence of best subtrees, as a function of <span class="math inline">\alpha</span>.</p></li>
<li><p>Use <span class="math inline">K</span>-fold cross-validation to choose <span class="math inline">\alpha</span>. For each <span class="math inline">k= 1,\ldots,K</span>:</p>
<p>3.1 Repeat Steps 1 and 2 on the <span class="math inline">\frac{K−1}{K}</span> th fraction of the training data, excluding the <span class="math inline">k</span>th fold.</p>
<p>3.2 Evaluate the mean squared prediction error on the data in the left-out kth fold, as a function of <span class="math inline">\alpha</span>. Average the results, and pick <span class="math inline">\alpha</span> to minimize the average error.</p></li>
</ol>
</section>
<section id="baseball-example-continued-4" class="slide level2 center">
<h2>Baseball example continued</h2>
<ul>
<li><p>First, we randomly divided the data set in half, yielding 132 observations in the training set and 131 observations in the test set.</p></li>
<li><p>We then built a large regression tree on the training data and varied <span class="math inline">\alpha</span> in in order to create subtrees with diﬀerent numbers of terminal nodes.</p></li>
<li><p>Finally, we performed six-fold cross-validation in order to estimate the cross-validated MSE of the trees as a function of <span class="math inline">\alpha</span>.</p></li>
</ul>
<ol start="4" type="1">
<li>Return the subtree from Step 2 that corresponds to the chosen value of <span class="math inline">\alpha</span>.</li>
</ol>
</section>
<section id="baseball-example-continued-isl-figure-8.4" class="slide level2 center">
<h2>Baseball example continued (ISL Figure 8.4)</h2>

<img data-src="img/8_4.png" style="width:80.0%" class="r-stretch"></section>
<section id="baseball-example-continued-isl-figure-8.5" class="slide level2 center">
<h2>Baseball example continued (ISL Figure 8.5)</h2>

<img data-src="img/8_5.png" style="width:80.0%" class="r-stretch"></section>
<section id="advantages-and-disadvantages-of-trees" class="slide level2 center">
<h2>Advantages and Disadvantages of Trees</h2>
<ul>
<li><p>Trees are very easy to explain to people. In fact, they are even easier to explain than linear regression!</p></li>
<li><p>Some people believe that decision trees more closely mirror human decision-making than do the regression approach seen in previous chapters.</p></li>
<li><p>Trees can be displayed graphically, and are easily interpreted even by a non-expert (especially if they are small).</p></li>
<li><p>Trees can easily handle qualitative predictors without the need to create dummy variables.</p></li>
<li><p>Unfortunately, trees generally do not have the same level of predictive accuracy as some of the other regression and classification approaches seen in this book.</p></li>
</ul>
<p>However, by aggregating many decision trees, the predictive performance of trees can be substantially improved. We introduce these concepts next.</p>
</section>
<section id="bagging" class="slide level2 center">
<h2>Bagging</h2>
<ul>
<li><p><span class="orange">Bootstrap aggregation</span>, or <span class="orange">bagging</span>, is a general-purpose procedure for reducing the variance of a statistical learning method; we introduce it here because it is particularly useful and frequently used in the context of decision trees.</p></li>
<li><p>Recall that given a set of <span class="math inline">n</span> independent observations <span class="math inline">Z_1,...,Z_n</span>, each with variance <span class="math inline">\sigma^2</span>, the variance of the mean <span class="math inline">Z</span> of the observations is given by <span class="math inline">\sigma^2/n</span>.</p></li>
<li><p>In other words, <span class="blue">averaging a set of observations reduces variance</span>. Of course, this is not practical because we generally do not have access to multiple training sets.</p></li>
</ul>
</section>
<section id="bagging---continued" class="slide level2 center">
<h2>Bagging - continued</h2>
<ul>
<li><p>Instead, we can bootstrap, by taking repeated samples from the (single) training data set.</p></li>
<li><p>In this approach we generate <span class="math inline">B</span> diﬀerent bootstrapped training data sets. We then train our method on the <span class="math inline">b</span>th bootstrapped training set in order to get <span class="math inline">\hat f^{*_b}(x)</span>, the prediction at a point <span class="math inline">x</span>. We then average all the predictions to obtain <span class="math display">\hat f_{bag}(x) = \frac{1}{B} \sum_{b=1}^{B} \hat f^{*_b}(x).</span> This is called <span class="orange">bagging</span>.</p></li>
</ul>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="img/cf_logo.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://aldosolari.github.io/ISL">ISL</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="un_D_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="un_D_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="un_D_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="un_D_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="un_D_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="un_D_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="un_D_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="un_D_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="un_D_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>