<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Aldo Solari">

<title>Tree-based Methods</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="un_D_files/libs/clipboard/clipboard.min.js"></script>
<script src="un_D_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="un_D_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="un_D_files/libs/quarto-html/popper.min.js"></script>
<script src="un_D_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="un_D_files/libs/quarto-html/anchor.min.js"></script>
<link href="un_D_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="un_D_files/libs/quarto-html/quarto-syntax-highlighting-234273d1456647dabc34a594ac50e507.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="un_D_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="un_D_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="un_D_files/libs/bootstrap/bootstrap-721140556699abb0ff907dddd6c78b98.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-full">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#regression-trees" id="toc-regression-trees" class="nav-link active" data-scroll-target="#regression-trees">Regression Trees</a></li>
  <li><a href="#pros-and-cons" id="toc-pros-and-cons" class="nav-link" data-scroll-target="#pros-and-cons">Pros and Cons</a></li>
  <li><a href="#baseball-salary-data-how-would-you-stratify-it" id="toc-baseball-salary-data-how-would-you-stratify-it" class="nav-link" data-scroll-target="#baseball-salary-data-how-would-you-stratify-it">Baseball salary data: how would you stratify it?</a></li>
  <li><a href="#decision-tree-for-these-data-isl-figure-8.1" id="toc-decision-tree-for-these-data-isl-figure-8.1" class="nav-link" data-scroll-target="#decision-tree-for-these-data-isl-figure-8.1">Decision tree for these data (ISL Figure 8.1)</a></li>
  <li><a href="#details-of-previous-figure" id="toc-details-of-previous-figure" class="nav-link" data-scroll-target="#details-of-previous-figure">Details of previous figure</a></li>
  <li><a href="#results-isl-figure-8.2" id="toc-results-isl-figure-8.2" class="nav-link" data-scroll-target="#results-isl-figure-8.2">Results (ISL Figure 8.2)</a></li>
  <li><a href="#terminology-for-trees" id="toc-terminology-for-trees" class="nav-link" data-scroll-target="#terminology-for-trees">Terminology for Trees</a></li>
  <li><a href="#interpretation-of-results" id="toc-interpretation-of-results" class="nav-link" data-scroll-target="#interpretation-of-results">Interpretation of Results</a></li>
  <li><a href="#details-of-the-tree-building-process" id="toc-details-of-the-tree-building-process" class="nav-link" data-scroll-target="#details-of-the-tree-building-process">Details of the tree-building process</a></li>
  <li><a href="#recursive-binary-splitting" id="toc-recursive-binary-splitting" class="nav-link" data-scroll-target="#recursive-binary-splitting">Recursive binary splitting</a></li>
  <li><a href="#recursive-binary-splitting-continued" id="toc-recursive-binary-splitting-continued" class="nav-link" data-scroll-target="#recursive-binary-splitting-continued">Recursive binary splitting — continued</a></li>
  <li><a href="#baseball-example" id="toc-baseball-example" class="nav-link" data-scroll-target="#baseball-example">Baseball example</a></li>
  <li><a href="#baseball-example-continued" id="toc-baseball-example-continued" class="nav-link" data-scroll-target="#baseball-example-continued">Baseball example continued</a></li>
  <li><a href="#baseball-example-continued-1" id="toc-baseball-example-continued-1" class="nav-link" data-scroll-target="#baseball-example-continued-1">Baseball example continued</a></li>
  <li><a href="#baseball-example-continued-2" id="toc-baseball-example-continued-2" class="nav-link" data-scroll-target="#baseball-example-continued-2">Baseball example continued</a></li>
  <li><a href="#baseball-example-continued-3" id="toc-baseball-example-continued-3" class="nav-link" data-scroll-target="#baseball-example-continued-3">Baseball example continued</a></li>
  <li><a href="#predictions" id="toc-predictions" class="nav-link" data-scroll-target="#predictions">Predictions</a></li>
  <li><a href="#isl-figure-8.3" id="toc-isl-figure-8.3" class="nav-link" data-scroll-target="#isl-figure-8.3">ISL Figure 8.3</a></li>
  <li><a href="#details-of-previous-figure-1" id="toc-details-of-previous-figure-1" class="nav-link" data-scroll-target="#details-of-previous-figure-1">Details of previous figure</a></li>
  <li><a href="#pruning-a-tree" id="toc-pruning-a-tree" class="nav-link" data-scroll-target="#pruning-a-tree">Pruning a tree</a></li>
  <li><a href="#pruning-a-tree---continued" id="toc-pruning-a-tree---continued" class="nav-link" data-scroll-target="#pruning-a-tree---continued">Pruning a tree - continued</a></li>
  <li><a href="#choosing-the-best-subtree" id="toc-choosing-the-best-subtree" class="nav-link" data-scroll-target="#choosing-the-best-subtree">Choosing the best subtree</a></li>
  <li><a href="#summary-tree-algorithm" id="toc-summary-tree-algorithm" class="nav-link" data-scroll-target="#summary-tree-algorithm">Summary: tree algorithm</a></li>
  <li><a href="#baseball-example-continued-4" id="toc-baseball-example-continued-4" class="nav-link" data-scroll-target="#baseball-example-continued-4">Baseball example continued</a></li>
  <li><a href="#baseball-example-continued-isl-figure-8.4" id="toc-baseball-example-continued-isl-figure-8.4" class="nav-link" data-scroll-target="#baseball-example-continued-isl-figure-8.4">Baseball example continued (ISL Figure 8.4)</a></li>
  <li><a href="#baseball-example-continued-isl-figure-8.5" id="toc-baseball-example-continued-isl-figure-8.5" class="nav-link" data-scroll-target="#baseball-example-continued-isl-figure-8.5">Baseball example continued (ISL Figure 8.5)</a></li>
  <li><a href="#advantages-and-disadvantages-of-trees" id="toc-advantages-and-disadvantages-of-trees" class="nav-link" data-scroll-target="#advantages-and-disadvantages-of-trees">Advantages and Disadvantages of Trees</a></li>
  <li><a href="#als-data" id="toc-als-data" class="nav-link" data-scroll-target="#als-data">ALS data</a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a></li>
  <li><a href="#bagging" id="toc-bagging" class="nav-link" data-scroll-target="#bagging">Bagging</a></li>
  <li><a href="#bagging---continued" id="toc-bagging---continued" class="nav-link" data-scroll-target="#bagging---continued">Bagging - continued</a></li>
  <li><a href="#bagging-the-als-data" id="toc-bagging-the-als-data" class="nav-link" data-scroll-target="#bagging-the-als-data">Bagging the ALS data</a></li>
  <li><a href="#details-of-previous-figure-2" id="toc-details-of-previous-figure-2" class="nav-link" data-scroll-target="#details-of-previous-figure-2">Details of previous figure</a></li>
  <li><a href="#out-of-bag-error-estimation" id="toc-out-of-bag-error-estimation" class="nav-link" data-scroll-target="#out-of-bag-error-estimation">Out-of-Bag Error Estimation</a></li>
  <li><a href="#boostrap-sample" id="toc-boostrap-sample" class="nav-link" data-scroll-target="#boostrap-sample">Boostrap Sample</a></li>
  <li><a href="#variable-importance" id="toc-variable-importance" class="nav-link" data-scroll-target="#variable-importance">Variable Importance</a></li>
  <li><a href="#random-forests" id="toc-random-forests" class="nav-link" data-scroll-target="#random-forests">Random Forests</a></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1"></a></li>
  <li><a href="#boosting" id="toc-boosting" class="nav-link" data-scroll-target="#boosting">Boosting</a></li>
  <li><a href="#boosting-algorithm-for-regression-trees" id="toc-boosting-algorithm-for-regression-trees" class="nav-link" data-scroll-target="#boosting-algorithm-for-regression-trees">Boosting algorithm for regression trees</a></li>
  <li><a href="#toy-example-b50-d1-lambda-0.01" id="toc-toy-example-b50-d1-lambda-0.01" class="nav-link" data-scroll-target="#toy-example-b50-d1-lambda-0.01">Toy Example (<span class="math inline">B=50, d=1, \lambda =0.01</span>)</a></li>
  <li><a href="#what-is-the-idea-behind-this-procedure" id="toc-what-is-the-idea-behind-this-procedure" class="nav-link" data-scroll-target="#what-is-the-idea-behind-this-procedure">What is the idea behind this procedure?</a></li>
  <li><a href="#tuning-parameters-for-boosting" id="toc-tuning-parameters-for-boosting" class="nav-link" data-scroll-target="#tuning-parameters-for-boosting">Tuning parameters for boosting</a></li>
  <li><a href="#casi-figure-17.6" id="toc-casi-figure-17.6" class="nav-link" data-scroll-target="#casi-figure-17.6">CASI, Figure 17.6</a></li>
  <li><a href="#casi-figure-17.8" id="toc-casi-figure-17.8" class="nav-link" data-scroll-target="#casi-figure-17.8">CASI Figure 17.8</a></li>
  <li><a href="#casi-figure-17.6-1" id="toc-casi-figure-17.6-1" class="nav-link" data-scroll-target="#casi-figure-17.6-1">CASI Figure 17.6</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#required-readings-from-the-textbook-and-course-materials" id="toc-required-readings-from-the-textbook-and-course-materials" class="nav-link" data-scroll-target="#required-readings-from-the-textbook-and-course-materials">Required readings from the textbook and course materials</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="un_C_slides.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
</div>
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tree-based Methods</h1>
<p class="subtitle lead">Introduction to Statistical Learning - PISE</p>
</div>


<div class="quarto-title-meta-author column-page-left">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author"><span class="orange">Aldo Solari</span> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            <em>Ca’ Foscari University of Venice</em>
          </p>
      </div>
  </div>

<div class="quarto-title-meta column-page-left">

      
  
    
  </div>
  


</header>


<p>This unit will cover the following <span class="orange">topics</span>:</p>
<ul>
<li>Regression Trees</li>
<li>Bagging</li>
<li>Random Forests</li>
<li>Boosting</li>
</ul>
<section id="regression-trees" class="level2">
<h2 class="anchored" data-anchor-id="regression-trees">Regression Trees</h2>
<ul>
<li><p>Tree-based methods involve <span class="orange">stratifying</span> or <span class="orange">segmenting</span> the predictor space into a number of simple regions.</p></li>
<li><p>Since the set of splitting rules used to segment the predictor space can be summarized in a tree, these types of approaches are known as <span class="orange">decision-tree</span> methods.</p></li>
</ul>
</section>
<section id="pros-and-cons" class="level2">
<h2 class="anchored" data-anchor-id="pros-and-cons">Pros and Cons</h2>
<ul>
<li><p>Tree-based methods are simple and useful for interpretation.</p></li>
<li><p>However they typically are not competitive with the best supervised learning approaches in terms of prediction accuracy.</p></li>
<li><p>Hence we also discuss <span class="blue">bagging</span>, <span class="blue">random forests</span>, and <span class="blue">boosting</span>. These methods grow multiple trees which are then combined to yield a single consensus prediction.</p></li>
<li><p>Combining a large number of trees can often result in dramatic improvements in prediction accuracy, at the expense of some loss interpretation.</p></li>
</ul>
</section>
<section id="baseball-salary-data-how-would-you-stratify-it" class="level2">
<h2 class="anchored" data-anchor-id="baseball-salary-data-how-would-you-stratify-it">Baseball salary data: how would you stratify it?</h2>
<p>Log Salary is color-coded from low (blue, green) to high (yellow,red)</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="un_D_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="750"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="decision-tree-for-these-data-isl-figure-8.1" class="level2">
<h2 class="anchored" data-anchor-id="decision-tree-for-these-data-isl-figure-8.1">Decision tree for these data (ISL Figure 8.1)</h2>
<p><img src="img/8_1.png" class="img-fluid" style="width:50.0%"></p>
</section>
<section id="details-of-previous-figure" class="level2">
<h2 class="anchored" data-anchor-id="details-of-previous-figure">Details of previous figure</h2>
<ul>
<li><p>For the Hitters data, a regression tree for predicting the log salary of a baseball player, based on the number of years that he has played in the major leagues and the number of hits that he made in the previous year.</p></li>
<li><p>At a given internal node, the label (of the form <span class="math inline">X_j &lt; t_k</span> ) indicates the left-hand branch emanating from that split, and the right-hand branch corresponds to <span class="math inline">X_j \geq t_k</span> . For instance, the split at the top of the tree results in two large branches. The left-hand branch corresponds to <code>Years</code>&lt;4.5, and the right-hand branch corresponds to <code>Years</code>&gt;=4.5.</p></li>
<li><p>The tree has two internal nodes and three terminal nodes, or leaves. The number in each leaf is the mean of the response for the observations that fall there.</p></li>
</ul>
</section>
<section id="results-isl-figure-8.2" class="level2">
<h2 class="anchored" data-anchor-id="results-isl-figure-8.2">Results (ISL Figure 8.2)</h2>
<p>Overall, the tree stratifies or segments the players into three regions of predictor space: <span class="math inline">R_1 =\{X |</span> <code>Years</code>&lt;4.5 <span class="math inline">\}</span>, <span class="math inline">R_2 =\{X |</span> <code>Years</code>&gt;=4.5, <code>Hits</code>&lt;117.5 <span class="math inline">\}</span>, and <span class="math inline">R_3 =\{X |</span> <code>Years</code>&gt;=4.5, <code>Hits</code>&gt;=117.5 <span class="math inline">\}</span>.</p>
<p><img src="img/8_2.png" class="img-fluid" style="width:80.0%"></p>
</section>
<section id="terminology-for-trees" class="level2">
<h2 class="anchored" data-anchor-id="terminology-for-trees">Terminology for Trees</h2>
<ul>
<li><p>In keeping with the tree analogy, the regions <span class="math inline">R_1</span>, <span class="math inline">R_2</span>, and <span class="math inline">R_3</span> are known as <span class="orange">terminal nodes</span></p></li>
<li><p>Decision trees are typically drawn <span class="blue">upside down</span>, in the sense that the leaves are at the bottom of the tree.</p></li>
<li><p>The points along the tree where the predictor space is split are referred to as <span class="orange">internal nodes</span></p></li>
<li><p>In the hitters tree, the two internal nodes are indicated by the text <code>Years</code>&lt;4.5 and <code>Hits</code>&lt;117.5.</p></li>
</ul>
</section>
<section id="interpretation-of-results" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-of-results">Interpretation of Results</h2>
<ul>
<li><p><code>Years</code> is the most important factor in determining <code>Salary</code>, and players with less experience earn lower salaries than more experienced players.</p></li>
<li><p>Given that a player is less experienced, the number of <code>Hits</code> that he made in the previous year seems to play little role in his Salary.</p></li>
<li><p>But among players who have been in the major leagues for five or more years, the number of <code>Hits</code> made in the previous year does affect <code>Salary</code>, and players who made more <code>Hits</code> last year tend to have higher salaries.</p></li>
<li><p>Surely an over-simplification, but compared to a regression model, it is easy to display, interpret and explain</p></li>
</ul>
</section>
<section id="details-of-the-tree-building-process" class="level2">
<h2 class="anchored" data-anchor-id="details-of-the-tree-building-process">Details of the tree-building process</h2>
<ul>
<li><p>Partition the predictor space (all values of <span class="math inline">X_1,\ldots,X_p</span>) into <span class="math inline">J</span> disjoint regions <span class="math inline">R_1,\ldots,R_J</span>.</p></li>
<li><p>In each region <span class="math inline">R_j</span>, predict with a constant: <span class="math display">
\hat{y}_{R_j} = \frac{1}{|R_j|} \sum_{i \in R_j} y_i
</span></p></li>
<li><p>Choose the regions to minimize the residual sum of squares (RSS): <span class="math display">
\sum_{j=1}^{J} \sum_{i \in R_j} (y_i - \hat{y}_{R_j})^2
</span></p></li>
<li><p>In practice, exhaustively searching over all possible partitions is computationally infeasible. Instead,</p>
<ul>
<li>restrict regions to <span class="blue">axis-aligned rectangles</span></li>
<li>build the partition using <span class="orange">recursive binary splitting</span> (top-down, greedy)</li>
</ul></li>
<li><p>Interpretation:</p>
<ul>
<li>each region = a group of similar observations<br>
</li>
<li>prediction = average response within that group</li>
</ul></li>
</ul>
</section>
<section id="recursive-binary-splitting" class="level2">
<h2 class="anchored" data-anchor-id="recursive-binary-splitting">Recursive binary splitting</h2>
<ul>
<li><p><span class="orange">Top-down</span>: start with the full dataset and successively split it into smaller regions.</p></li>
<li><p><span class="orange">Greedy</span>: at each step, choose the split that gives the largest immediate reduction in RSS.</p></li>
<li><p>At each step, select a predictor <span class="math inline">X_j</span> and split point <span class="math inline">s</span> that divides a region into: <span class="math display">
R_1(j,s) = \{X \mid X_j &lt; s\}, \quad
R_2(j,s) = \{X \mid X_j \ge s\}.
</span></p></li>
<li><p>Choose <span class="math inline">(j,s)</span> to minimize: <span class="math display">
\text{RSS}(j,s) =
\sum_{i \in R_1(j,s)} (y_i - \hat{y}_{R_1})^2 +
\sum_{i \in R_2(j,s)} (y_i - \hat{y}_{R_2})^2.
</span></p></li>
<li><p>In practice:</p>
<ul>
<li>sort each predictor</li>
<li>evaluate splits at <span class="blue">midpoints between consecutive values</span></li>
<li>select the split with smallest RSS</li>
</ul></li>
</ul>
</section>
<section id="recursive-binary-splitting-continued" class="level2">
<h2 class="anchored" data-anchor-id="recursive-binary-splitting-continued">Recursive binary splitting — continued</h2>
<ul>
<li><p>After the first split, we obtain two regions <span class="math inline">R_1</span> and <span class="math inline">R_2</span>.</p></li>
<li><p>Next, we split <span class="blue">one of these regions</span> further.</p></li>
<li><p>For <span class="math inline">R \in \{R_1, R_2\}</span>, define: <span class="math display">
R_L(j,s;R) = \{X \in R \mid X_j &lt; s\}, \quad
R_R(j,s;R) = \{X \in R \mid X_j \ge s\}.
</span></p></li>
<li><p>Choose <span class="math inline">R</span>, <span class="math inline">j</span>, and <span class="math inline">s</span> to minimize the <span class="orange">total RSS after the split</span>:</p></li>
</ul>
<p><span class="math display">\sum_{i \in R_L(j,s;R)} (y_i - \hat{y}_L)^2
+
\sum_{i \in R_R(j,s;R)} (y_i - \hat{y}_R)^2
+
\sum_{i \in R^c} (y_i - \hat{y}_{R^c})^2,</span> where <span class="math inline">R^c</span> is the region not split.</p>
<ul>
<li>Repeat until a stopping rule is met (e.g., minimum node size).</li>
</ul>
</section>
<section id="baseball-example" class="level2">
<h2 class="anchored" data-anchor-id="baseball-example">Baseball example</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    predictor split      RSS
1       Years   1.5 5.371093
2       Years   2.5 4.396926
3       Years   3.5 3.459744
4       Years   4.5 3.397360
5       Years   5.5 3.998963
6       Years   6.5 4.528329
7       Years   7.5 5.015692
8       Years   8.5 5.160630
9       Years   9.5 5.441011
10      Years  10.5 5.549537
11      Years  11.5 5.717716
12      Years  12.5 5.779519
13      Years  13.5 6.017264
14      Years  14.5 6.180344
15      Years  15.5 6.228585
16      Years  16.5 6.238226
17      Years  17.5 6.263735
18      Years  18.5 6.295138
19      Years  19.5 6.297833
20      Years  22.0 6.284817
21       Hits   2.5 6.227453
22       Hits  15.5 6.210460
23       Hits  29.5 6.267218
24       Hits  34.5 6.292269
25       Hits  38.0 6.296987
26       Hits  39.5 6.258108
27       Hits  40.5 6.221868
28       Hits  41.5 6.117778
29       Hits  42.5 6.162232
30       Hits  43.5 6.127846
31       Hits  45.0 6.128328
32       Hits  46.5 6.095667
33       Hits  48.0 6.108631
34       Hits  50.0 6.120371
35       Hits  51.5 6.066072
36       Hits  52.5 6.105733
37       Hits  53.5 6.011732
38       Hits  54.5 5.894460
39       Hits  55.5 5.948283
40       Hits  56.5 5.871224
41       Hits  57.5 5.836472
42       Hits  59.0 5.790090
43       Hits  60.5 5.740105
44       Hits  62.0 5.732392
45       Hits  63.5 5.740384
46       Hits  64.5 5.675512
47       Hits  65.5 5.709179
48       Hits  67.0 5.648360
49       Hits  68.5 5.593724
50       Hits  69.5 5.592256
51       Hits  70.5 5.654370
52       Hits  71.5 5.605030
53       Hits  72.5 5.567728
54       Hits  73.5 5.504112
55       Hits  74.5 5.540488
56       Hits  75.5 5.505728
57       Hits  76.5 5.473642
58       Hits  77.5 5.534621
59       Hits  79.0 5.495257
60       Hits  80.5 5.526392
61       Hits  81.5 5.497471
62       Hits  82.5 5.462044
63       Hits  83.5 5.512501
64       Hits  84.5 5.554221
65       Hits  85.5 5.556012
66       Hits  86.5 5.499711
67       Hits  88.5 5.442760
68       Hits  90.5 5.455674
69       Hits  91.5 5.448321
70       Hits  92.5 5.399763
71       Hits  93.5 5.367207
72       Hits  94.5 5.445048
73       Hits  95.5 5.390645
74       Hits  96.5 5.372025
75       Hits  98.0 5.351532
76       Hits 100.0 5.286660
77       Hits 101.5 5.280756
78       Hits 102.5 5.215843
79       Hits 103.5 5.095537
80       Hits 105.0 5.128264
81       Hits 107.0 5.165339
82       Hits 108.5 5.082224
83       Hits 109.5 5.023407
84       Hits 111.0 5.093273
85       Hits 112.5 5.075512
86       Hits 113.5 5.058192
87       Hits 114.5 5.070028
88       Hits 115.5 5.060329
89       Hits 116.5 5.082123
90       Hits 117.5 4.951691
91       Hits 118.5 4.960297
92       Hits 119.5 5.055826
93       Hits 121.0 5.000380
94       Hits 122.5 5.011493
95       Hits 123.5 5.112514
96       Hits 124.5 5.128384
97       Hits 125.5 5.193194
98       Hits 126.5 5.220114
99       Hits 127.5 5.258931
100      Hits 128.5 5.328320
101      Hits 129.5 5.354354
102      Hits 130.5 5.362508
103      Hits 131.5 5.432370
104      Hits 132.5 5.441132
105      Hits 134.0 5.466626
106      Hits 135.5 5.453692
107      Hits 136.5 5.533691
108      Hits 137.5 5.558262
109      Hits 138.5 5.470874
110      Hits 139.5 5.458108
111      Hits 140.5 5.424153
112      Hits 141.5 5.472159
113      Hits 143.0 5.451446
114      Hits 144.5 5.497305
115      Hits 145.5 5.453744
116      Hits 146.5 5.480040
117      Hits 147.5 5.542276
118      Hits 148.5 5.616462
119      Hits 149.5 5.585710
120      Hits 150.5 5.618275
121      Hits 151.5 5.681251
122      Hits 153.0 5.655225
123      Hits 155.5 5.686073
124      Hits 157.5 5.696370
125      Hits 158.5 5.732919
126      Hits 159.5 5.771076
127      Hits 160.5 5.819672
128      Hits 162.0 5.831730
129      Hits 165.0 5.913516
130      Hits 167.5 5.878046
131      Hits 168.5 5.943581
132      Hits 169.5 5.992036
133      Hits 170.5 6.054076
134      Hits 171.5 6.120273
135      Hits 173.0 6.079299
136      Hits 175.5 6.118865
137      Hits 177.5 6.153522
138      Hits 178.5 6.168823
139      Hits 181.0 6.175956
140      Hits 183.5 6.192442
141      Hits 185.0 6.202358
142      Hits 192.0 6.232277
143      Hits 199.0 6.256697
144      Hits 203.5 6.278593
145      Hits 208.5 6.296776
146      Hits 210.5 6.261997
147      Hits 212.0 6.276003
148      Hits 218.0 6.264215
149      Hits 230.5 6.232610</code></pre>
</div>
</div>
</section>
<section id="baseball-example-continued" class="level2">
<h2 class="anchored" data-anchor-id="baseball-example-continued">Baseball example continued</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="un_D_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="750"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="baseball-example-continued-1" class="level2">
<h2 class="anchored" data-anchor-id="baseball-example-continued-1">Baseball example continued</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Left region (Years &lt; 4.50): n = 90, mean log-Salary = 1.622</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Right region (Years &gt;= 4.50): n = 173, mean log-Salary = 1.844</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Interpretation:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>The split at Years = 4.50 creates two regions.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>The left region contains 90 players and is assigned the prediction 1.622.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>The right region contains 173 players and is assigned the prediction 1.844.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Because the response is log(Salary), these are predicted mean log-salaries in the two regions.</code></pre>
</div>
</div>
</section>
<section id="baseball-example-continued-2" class="level2">
<h2 class="anchored" data-anchor-id="baseball-example-continued-2">Baseball example continued</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="un_D_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="750"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="baseball-example-continued-3" class="level2">
<h2 class="anchored" data-anchor-id="baseball-example-continued-3">Baseball example continued</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    region predictor split region_RSS total_RSS
1     Left     Years   1.5   1.319332  3.261867
2     Left     Years   2.5   1.207432  3.149967
3     Left     Years   3.5   1.112303  3.054837
4     Left      Hits   2.5   1.281382  3.223916
5     Left      Hits  15.5   1.195274  3.137809
6     Left      Hits  32.0   1.261950  3.204485
7     Left      Hits  38.0   1.369151  3.311686
8     Left      Hits  39.5   1.418755  3.361290
9     Left      Hits  40.5   1.439334  3.381869
10    Left      Hits  42.0   1.454823  3.397358
11    Left      Hits  44.5   1.454490  3.397025
12    Left      Hits  48.5   1.454743  3.397278
13    Left      Hits  52.0   1.450571  3.393106
14    Left      Hits  53.5   1.436085  3.378620
15    Left      Hits  55.0   1.404618  3.347153
16    Left      Hits  56.5   1.403503  3.346038
17    Left      Hits  57.5   1.402668  3.345203
18    Left      Hits  59.0   1.407750  3.350285
19    Left      Hits  62.0   1.394341  3.336875
20    Left      Hits  65.0   1.376087  3.318622
21    Left      Hits  67.0   1.361891  3.304426
22    Left      Hits  68.5   1.337789  3.280323
23    Left      Hits  69.5   1.356119  3.298653
24    Left      Hits  70.5   1.369962  3.312497
25    Left      Hits  72.0   1.358715  3.301249
26    Left      Hits  74.0   1.337515  3.280050
27    Left      Hits  75.5   1.335522  3.278057
28    Left      Hits  77.0   1.349370  3.291905
29    Left      Hits  79.5   1.324547  3.267081
30    Left      Hits  81.5   1.299983  3.242518
31    Left      Hits  84.0   1.288557  3.231092
32    Left      Hits  86.5   1.292939  3.235474
33    Left      Hits  89.0   1.273747  3.216282
34    Left      Hits  91.5   1.265881  3.208416
35    Left      Hits  92.5   1.245869  3.188403
36    Left      Hits  94.5   1.244122  3.186657
37    Left      Hits  96.5   1.261724  3.204258
38    Left      Hits  98.0   1.271392  3.213927
39    Left      Hits 100.0   1.247694  3.190229
40    Left      Hits 102.0   1.234213  3.176748
41    Left      Hits 105.5   1.193858  3.136392
42    Left      Hits 108.5   1.186047  3.128582
43    Left      Hits 110.5   1.168522  3.111057
44    Left      Hits 112.5   1.157854  3.100388
45    Left      Hits 113.5   1.174403  3.116938
46    Left      Hits 114.5   1.214848  3.157383
47    Left      Hits 116.0   1.236536  3.179071
48    Left      Hits 117.5   1.220602  3.163136
49    Left      Hits 119.0   1.215231  3.157766
50    Left      Hits 121.0   1.216359  3.158894
51    Left      Hits 122.5   1.243324  3.185859
52    Left      Hits 125.0   1.306566  3.249101
53    Left      Hits 128.5   1.311264  3.253799
54    Left      Hits 131.0   1.341955  3.284490
55    Left      Hits 133.5   1.348074  3.290609
56    Left      Hits 136.0   1.347069  3.289604
57    Left      Hits 137.5   1.346365  3.288900
58    Left      Hits 138.5   1.334082  3.276617
59    Left      Hits 139.5   1.328692  3.271226
60    Left      Hits 141.0   1.331225  3.273760
61    Left      Hits 143.0   1.305769  3.248304
62    Left      Hits 144.5   1.298338  3.240873
63    Left      Hits 147.0   1.286423  3.228958
64    Left      Hits 150.5   1.266658  3.209193
65    Left      Hits 154.5   1.263775  3.206310
66    Left      Hits 159.0   1.317537  3.260071
67    Left      Hits 162.0   1.365265  3.307800
68    Left      Hits 165.0   1.412458  3.354992
69    Left      Hits 169.5   1.414429  3.356963
70    Left      Hits 186.0   1.403780  3.346315
71    Left      Hits 206.5   1.409318  3.351853
72    Left      Hits 218.0   1.431238  3.373773
73   Right     Years   5.5   1.890172  3.344997
74   Right     Years   6.5   1.862262  3.317088
75   Right     Years   7.5   1.899725  3.354551
76   Right     Years   8.5   1.894117  3.348943
77   Right     Years   9.5   1.918929  3.373755
78   Right     Years  10.5   1.910833  3.365658
79   Right     Years  11.5   1.926658  3.381484
80   Right     Years  12.5   1.917794  3.372620
81   Right     Years  13.5   1.941244  3.396070
82   Right     Years  14.5   1.939608  3.394433
83   Right     Years  15.5   1.937982  3.392808
84   Right     Years  16.5   1.940613  3.395439
85   Right     Years  17.5   1.940793  3.395619
86   Right     Years  18.5   1.935372  3.390198
87   Right     Years  19.5   1.934844  3.389670
88   Right     Years  22.0   1.940362  3.395188
89   Right      Hits  35.5   1.905647  3.360472
90   Right      Hits  40.0   1.853547  3.308372
91   Right      Hits  41.5   1.836484  3.291309
92   Right      Hits  42.5   1.870942  3.325768
93   Right      Hits  43.5   1.837118  3.291943
94   Right      Hits  45.0   1.821850  3.276676
95   Right      Hits  46.5   1.785473  3.240298
96   Right      Hits  48.0   1.769784  3.224610
97   Right      Hits  50.5   1.754470  3.209296
98   Right      Hits  52.5   1.756907  3.211732
99   Right      Hits  53.5   1.763409  3.218234
100  Right      Hits  54.5   1.750200  3.205025
101  Right      Hits  55.5   1.783477  3.238302
102  Right      Hits  56.5   1.734586  3.189412
103  Right      Hits  58.5   1.713946  3.168771
104  Right      Hits  60.5   1.729375  3.184200
105  Right      Hits  62.0   1.706809  3.161635
106  Right      Hits  64.0   1.697793  3.152618
107  Right      Hits  65.5   1.710242  3.165068
108  Right      Hits  67.0   1.689751  3.144577
109  Right      Hits  69.0   1.638327  3.093153
110  Right      Hits  71.0   1.619347  3.074173
111  Right      Hits  72.5   1.569242  3.024068
112  Right      Hits  73.5   1.584380  3.039205
113  Right      Hits  75.0   1.600044  3.054870
114  Right      Hits  76.5   1.559086  3.013912
115  Right      Hits  77.5   1.550198  3.005024
116  Right      Hits  79.0   1.546833  3.001659
117  Right      Hits  80.5   1.559109  3.013935
118  Right      Hits  81.5   1.546203  3.001029
119  Right      Hits  82.5   1.541340  2.996165
120  Right      Hits  83.5   1.539928  2.994753
121  Right      Hits  84.5   1.547334  3.002160
122  Right      Hits  87.5   1.518498  2.973323
123  Right      Hits  90.5   1.514591  2.969416
124  Right      Hits  91.5   1.529982  2.984807
125  Right      Hits  92.5   1.535315  2.990141
126  Right      Hits  93.5   1.522493  2.977319
127  Right      Hits  94.5   1.544159  2.998985
128  Right      Hits  95.5   1.481903  2.936729
129  Right      Hits  98.5   1.473359  2.928185
130  Right      Hits 101.5   1.494732  2.949557
131  Right      Hits 102.5   1.408901  2.863727
132  Right      Hits 103.5   1.362936  2.817762
133  Right      Hits 105.0   1.374593  2.829419
134  Right      Hits 108.0   1.390211  2.845036
135  Right      Hits 111.0   1.399984  2.854809
136  Right      Hits 112.5   1.410489  2.865315
137  Right      Hits 114.5   1.410618  2.865444
138  Right      Hits 116.5   1.413036  2.867861
139  Right      Hits 117.5   1.340177  2.795003
140  Right      Hits 118.5   1.369027  2.823853
141  Right      Hits 119.5   1.399491  2.854316
142  Right      Hits 121.0   1.401063  2.855888
143  Right      Hits 122.5   1.398414  2.853239
144  Right      Hits 123.5   1.424181  2.879007
145  Right      Hits 124.5   1.422297  2.877122
146  Right      Hits 125.5   1.459717  2.914542
147  Right      Hits 126.5   1.452736  2.907561
148  Right      Hits 127.5   1.480455  2.935281
149  Right      Hits 128.5   1.508295  2.963120
150  Right      Hits 130.0   1.515504  2.970330
151  Right      Hits 131.5   1.531565  2.986390
152  Right      Hits 132.5   1.546970  3.001796
153  Right      Hits 134.0   1.554371  3.009197
154  Right      Hits 135.5   1.560725  3.015551
155  Right      Hits 136.5   1.586109  3.040935
156  Right      Hits 138.0   1.608953  3.063779
157  Right      Hits 140.0   1.607801  3.062627
158  Right      Hits 141.5   1.606954  3.061780
159  Right      Hits 143.0   1.630102  3.084927
160  Right      Hits 144.5   1.670967  3.125793
161  Right      Hits 145.5   1.664383  3.119209
162  Right      Hits 146.5   1.671245  3.126071
163  Right      Hits 147.5   1.681078  3.135903
164  Right      Hits 148.5   1.710290  3.165116
165  Right      Hits 149.5   1.715615  3.170440
166  Right      Hits 150.5   1.726839  3.181665
167  Right      Hits 151.5   1.757708  3.212534
168  Right      Hits 153.0   1.766136  3.220962
169  Right      Hits 155.5   1.767103  3.221928
170  Right      Hits 157.5   1.755593  3.210419
171  Right      Hits 158.5   1.759961  3.214787
172  Right      Hits 159.5   1.755237  3.210062
173  Right      Hits 161.5   1.778057  3.232882
174  Right      Hits 165.5   1.815637  3.270463
175  Right      Hits 168.5   1.830561  3.285387
176  Right      Hits 169.5   1.835031  3.289856
177  Right      Hits 170.5   1.857940  3.312766
178  Right      Hits 172.5   1.884522  3.339348
179  Right      Hits 175.5   1.893130  3.347956
180  Right      Hits 177.5   1.906263  3.361089
181  Right      Hits 178.5   1.908438  3.363264
182  Right      Hits 181.0   1.905610  3.360435
183  Right      Hits 183.5   1.908464  3.363290
184  Right      Hits 185.0   1.906777  3.361603
185  Right      Hits 192.0   1.919686  3.374512
186  Right      Hits 199.0   1.929488  3.384314
187  Right      Hits 203.5   1.942069  3.396894
188  Right      Hits 208.5   1.938267  3.393093
189  Right      Hits 210.5   1.916370  3.371196
190  Right      Hits 224.5   1.908858  3.363683</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Best second split:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Split the Right region</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Predictor: Hits</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Split point: 117.50</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Region RSS after split: 1.340</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Total RSS after second split: 2.795</code></pre>
</div>
</div>
</section>
<section id="predictions" class="level2">
<h2 class="anchored" data-anchor-id="predictions">Predictions</h2>
<ul>
<li><p>For a new observation, predict using the <span class="blue">mean response in its region</span>.</p></li>
<li><p>The model is a <span class="blue">piecewise-constant function</span> over the predictor space.</p></li>
<li><p>A five-region example of this approach is shown in the next slide.</p></li>
</ul>
</section>
<section id="isl-figure-8.3" class="level2">
<h2 class="anchored" data-anchor-id="isl-figure-8.3">ISL Figure 8.3</h2>
<p><img src="img/8_3.png" class="img-fluid" style="width:80.0%"></p>
</section>
<section id="details-of-previous-figure-1" class="level2">
<h2 class="anchored" data-anchor-id="details-of-previous-figure-1">Details of previous figure</h2>
<ul>
<li><p><span class="orange">Top Left</span>: A partition of two-dimensional feature space that could not result from recursive binary splitting.</p></li>
<li><p><span class="orange">Top Right</span>: The output of recursive binary splitting on a two-dimensional example.</p></li>
<li><p><span class="orange">Bottom Left</span>: A tree corresponding to the partition in the top right panel.</p></li>
<li><p><span class="orange">Bottom Right</span>: A perspective plot of the prediction surface corresponding to that tree.</p></li>
</ul>
</section>
<section id="pruning-a-tree" class="level2">
<h2 class="anchored" data-anchor-id="pruning-a-tree">Pruning a tree</h2>
<ul>
<li><p>The process described above may produce good predictions on the training set, but is likely to <span class="blue">overfit</span> the data, leading to poor test set performance. <span class="blue">Why?</span></p></li>
<li><p>A smaller tree with fewer splits (that is, fewer regions <span class="math inline">R_1,\ldots,R_J</span> ) might lead to lower variance and better interpretation at the cost of a little bias.</p></li>
<li><p>One possible alternative to the process described above is to grow the tree only so long as the decrease in the RSS due to each split exceeds some (high) threshold.</p></li>
<li><p>This strategy will result in smaller trees, but is too <span class="blue">short-sighted</span>: a seemingly worthless split early on in the tree might be followed by a very good split — that is, a split that leads to a large reduction in RSS later on.</p></li>
</ul>
</section>
<section id="pruning-a-tree---continued" class="level2">
<h2 class="anchored" data-anchor-id="pruning-a-tree---continued">Pruning a tree - continued</h2>
<ul>
<li><p>A better strategy is to grow a very large tree <span class="math inline">T_0</span>, and then <span class="orange">prune</span> it back in order to obtain a <span class="orange">subtree</span></p></li>
<li><p><span class="orange">Cost complexity pruning</span> — also known as <span class="orange">weakest link pruning</span> — is used to do this</p></li>
<li><p>we consider a sequence of trees indexed by a nonnegative tuning parameter <span class="math inline">\alpha</span>. For each value of <span class="math inline">\alpha</span> there corresponds a subtree <span class="math inline">T \subset T_0</span> such that <span class="math display">\sum_{m=1}^{|T|} \sum_{i: x_i \in R_m}(y_i - \hat{y}_{R_m})^2 + \alpha |T|</span> is as small as possible. Here <span class="math inline">|T|</span> indicates the number of terminal nodes of the tree <span class="math inline">T</span>, <span class="math inline">R_m</span> is the rectangle (i.e.&nbsp;the subset of predictor space) corresponding to the <span class="math inline">m</span>th terminal node, and <span class="math inline">\hat{y}_{R_m}</span> is the mean of the training observations in <span class="math inline">R_m</span>.</p></li>
</ul>
</section>
<section id="choosing-the-best-subtree" class="level2">
<h2 class="anchored" data-anchor-id="choosing-the-best-subtree">Choosing the best subtree</h2>
<ul>
<li><p>The tuning parameter <span class="math inline">\alpha</span> controls a trade-oﬀ between the subtree’s complexity and its fit to the training data.</p></li>
<li><p>We select an optimal value <span class="math inline">\hat \alpha</span> using cross-validation.</p></li>
<li><p>We then return to the full data set and obtain the subtree corresponding to <span class="math inline">\hat \alpha</span></p></li>
</ul>
</section>
<section id="summary-tree-algorithm" class="level2">
<h2 class="anchored" data-anchor-id="summary-tree-algorithm">Summary: tree algorithm</h2>
<ol type="1">
<li><p>Use recursive binary splitting to grow a large tree on the training data, stopping only when each terminal node has fewer than some minimum number of observations.</p></li>
<li><p>Apply cost complexity pruning to the large tree in order to obtain a sequence of best subtrees, as a function of <span class="math inline">\alpha</span>.</p></li>
<li><p>Use <span class="math inline">K</span>-fold cross-validation to choose <span class="math inline">\alpha</span>. For each <span class="math inline">k= 1,\ldots,K</span>:</p>
<p>3.1 Repeat Steps 1 and 2 on the <span class="math inline">\frac{K−1}{K}</span> th fraction of the training data, excluding the <span class="math inline">k</span>th fold.</p>
<p>3.2 Evaluate the mean squared prediction error on the data in the left-out kth fold, as a function of <span class="math inline">\alpha</span>. Average the results, and pick <span class="math inline">\alpha</span> to minimize the average error.</p></li>
</ol>
</section>
<section id="baseball-example-continued-4" class="level2">
<h2 class="anchored" data-anchor-id="baseball-example-continued-4">Baseball example continued</h2>
<ul>
<li><p>First, we randomly divided the data set in half, yielding 132 observations in the training set and 131 observations in the test set.</p></li>
<li><p>We then built a large regression tree on the training data and varied <span class="math inline">\alpha</span> in in order to create subtrees with diﬀerent numbers of terminal nodes.</p></li>
<li><p>Finally, we performed six-fold cross-validation in order to estimate the cross-validated MSE of the trees as a function of <span class="math inline">\alpha</span>.</p></li>
</ul>
<ol start="4" type="1">
<li>Return the subtree from Step 2 that corresponds to the chosen value of <span class="math inline">\alpha</span>.</li>
</ol>
</section>
<section id="baseball-example-continued-isl-figure-8.4" class="level2">
<h2 class="anchored" data-anchor-id="baseball-example-continued-isl-figure-8.4">Baseball example continued (ISL Figure 8.4)</h2>
<p><img src="img/8_4.png" class="img-fluid" style="width:80.0%"></p>
</section>
<section id="baseball-example-continued-isl-figure-8.5" class="level2">
<h2 class="anchored" data-anchor-id="baseball-example-continued-isl-figure-8.5">Baseball example continued (ISL Figure 8.5)</h2>
<p><img src="img/8_5.png" class="img-fluid" style="width:80.0%"></p>
</section>
<section id="advantages-and-disadvantages-of-trees" class="level2">
<h2 class="anchored" data-anchor-id="advantages-and-disadvantages-of-trees">Advantages and Disadvantages of Trees</h2>
<ul>
<li><p>Trees are very easy to explain to people. In fact, they are even easier to explain than linear regression!</p></li>
<li><p>Some people believe that decision trees more closely mirror human decision-making than do the regression approach seen in previous chapters.</p></li>
<li><p>Trees can be displayed graphically, and are easily interpreted even by a non-expert (especially if they are small).</p></li>
<li><p>Trees can easily handle qualitative predictors without the need to create dummy variables.</p></li>
<li><p>Unfortunately, trees generally do not have the same level of predictive accuracy as some of the other regression and classification approaches seen in this book.</p></li>
</ul>
<p>However, by aggregating many decision trees, the predictive performance of trees can be substantially improved. We introduce these concepts next.</p>
</section>
<section id="als-data" class="level2">
<h2 class="anchored" data-anchor-id="als-data">ALS data</h2>
<ul>
<li><p>These data concern amyotrophic lateral sclerosis (Lou Gerig’s disease). There are 1822 observations (<span class="math inline">n=1197</span> training set and <span class="math inline">625</span> test set) on individuals with ALS. See <a href="https://lmackey.github.io/papers/als-nbt14.pdf">Kuffner et al.&nbsp;Nature Biotechnol. 33, 51–57; 2015</a></p></li>
<li><p>The goal is to predict the rate of progression <code>dFRS</code> of a functional rating score, using <span class="math inline">p=369</span> predictors based on measurements (and derivatives of these) obtained from patient visits.</p></li>
<li><p>These data can be read directly into R via the command</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a>als <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"http://hastie.su.domains/CASI_files/DATA/ALS.txt"</span>,<span class="at">header=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section"></h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="un_D_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="900"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="un_D_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid figure-img" width="900"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="un_D_files/figure-html/unnamed-chunk-9-3.png" class="img-fluid figure-img" width="900"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="un_D_files/figure-html/unnamed-chunk-9-4.png" class="img-fluid figure-img" width="900"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Test set MSE : 0.2788"</code></pre>
</div>
</div>
</section>
<section id="bagging" class="level2">
<h2 class="anchored" data-anchor-id="bagging">Bagging</h2>
<ul>
<li><p><span class="orange">Bootstrap aggregation</span>, or <span class="orange">bagging</span>, is a general-purpose procedure for reducing the variance of a statistical learning method; we introduce it here because it is particularly useful and frequently used in the context of decision trees.</p></li>
<li><p>Recall that given a set of <span class="math inline">n</span> independent observations <span class="math inline">Z_1,...,Z_n</span>, each with variance <span class="math inline">\sigma^2</span>, the variance of the mean <span class="math inline">Z</span> of the observations is given by <span class="math inline">\sigma^2/n</span>.</p></li>
<li><p>In other words, <span class="blue">averaging a set of observations reduces variance</span>. Of course, this is not practical because we generally do not have access to multiple training sets.</p></li>
</ul>
</section>
<section id="bagging---continued" class="level2">
<h2 class="anchored" data-anchor-id="bagging---continued">Bagging - continued</h2>
<ul>
<li><p>Instead, we can bootstrap, by taking repeated samples from the (single) training data set.</p></li>
<li><p>In this approach we generate <span class="math inline">B</span> diﬀerent bootstrapped training data sets. We then train our method on the <span class="math inline">b</span>th bootstrapped training set in order to get <span class="math inline">\hat f^{*_b}(x)</span>, the prediction at a point <span class="math inline">x</span>. We then average all the predictions to obtain <span class="math display">\hat f_{bag}(x) = \frac{1}{B} \sum_{b=1}^{B} \hat f^{*_b}(x).</span> This is called <span class="orange">bagging</span>.</p></li>
</ul>
</section>
<section id="bagging-the-als-data" class="level2">
<h2 class="anchored" data-anchor-id="bagging-the-als-data">Bagging the ALS data</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="un_D_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="900"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="details-of-previous-figure-2" class="level2">
<h2 class="anchored" data-anchor-id="details-of-previous-figure-2">Details of previous figure</h2>
<p>Bagging results for the ALS data.</p>
<ul>
<li><p>The test error (black) is shown as a function of <span class="math inline">B</span>, the number of bootstrapped training sets used.</p></li>
<li><p>The dashed line indicates the test error resulting from a single classification tree.</p></li>
<li><p>The blue traces show the OOB error, which in this case is considerably higher</p></li>
</ul>
</section>
<section id="out-of-bag-error-estimation" class="level2">
<h2 class="anchored" data-anchor-id="out-of-bag-error-estimation">Out-of-Bag Error Estimation</h2>
<p>It turns out that there is a very straightforward way to estimate the test error of a bagged model.</p>
<ul>
<li><p>Recall that the key to bagging is that trees are repeatedly fit to bootstrapped subsets of the observations. One can show that on average, each bagged tree makes use of around two-thirds of the observations.</p></li>
<li><p>The remaining one-third of the observations not used to fit a given bagged tree are referred to as the out-of-bag (OOB) observations.</p></li>
<li><p>We can predict the response for the ith observation using each of the trees in which that observation was OOB. This will yield around <span class="math inline">B/3</span> predictions for the ith observation, which we average.</p></li>
<li><p>This estimate is essentially the LOO cross-validation error for bagging, if <span class="math inline">B</span> is large.</p></li>
</ul>
</section>
<section id="boostrap-sample" class="level2">
<h2 class="anchored" data-anchor-id="boostrap-sample">Boostrap Sample</h2>
<ul>
<li><p>A bootstrap sample of size <span class="math inline">n</span> drawn from the training data is <span class="math display">(\tilde x_1, \tilde y_1), \ldots, (\tilde x_n, \tilde y_n),</span> where each pair <span class="math inline">(\tilde x_i, \tilde y_i)</span> is selected independently and with replacement, uniformly at random from the original dataset <span class="math display">(x_1, y_1), \ldots, (x_n, y_n),</span></p></li>
<li><p>In a bootstrap sample of size <span class="math inline">n</span>, some observations appear multiple times, while others are not selected. For a single draw, the probability that a specific observation is not chosen is <span class="math display">1-\frac{1}{n}</span></p></li>
<li><p>After <span class="math inline">n</span> draws (i.e., one bootstrap sample), the probability that a given observation is never selected is <span class="math display">\Big(1-\frac{1}{n}\Big)^n \approx \frac{1}{e} \approx 0.368</span> for large <span class="math inline">n</span>. Thus, about 1/3 of the training observations are left out of a given bootstrap sample</p></li>
</ul>
</section>
<section id="variable-importance" class="level2">
<h2 class="anchored" data-anchor-id="variable-importance">Variable Importance</h2>
<ul>
<li><p>How can we measure variable importance?</p></li>
<li><p>In bagging, and more generally random forests, a common approach is based on <span class="blue">permuting predictors</span> using the out-of-bag (OOB) data.</p></li>
<li><p>For each tree, the prediction error on its OOB sample is computed (OOB MSE). Then, for a given predictor, its values are randomly permuted in the OOB data and the prediction error is recomputed.</p></li>
<li><p>The increase in prediction error due to this permutation is averaged over all trees, and often normalized by the standard deviation of these increases.</p></li>
<li><p>This measures how much worse the model performs when the information in a variable is destroyed, i.e., it compares the model’s performance using the original variable versus a randomized version of it.</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="un_D_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="900"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="random-forests" class="level2">
<h2 class="anchored" data-anchor-id="random-forests">Random Forests</h2>
<p><span class="orange">Random forests</span> provide an improvement over bagged trees by way of a small tweak that <span class="blue">decorrelates</span> the trees. This reduces the variance when we average the trees.</p>
<ul>
<li><p>As in bagging, we build a number of decision trees on bootstrapped training samples.</p></li>
<li><p>But when building these decision trees, each time a split in a tree is considered, <span class="blue">a random selection of <span class="math inline">m</span> predictors</span> is chosen as split candidates from the full set of <span class="math inline">p</span> predictors. The split is allowed to use only one of those <span class="math inline">m</span> predictors.</p></li>
<li><p>A fresh selection of <span class="math inline">m</span> predictors is taken at each split, and typically we choose <span class="math inline">m \approx \sqrt{p}</span> — that is, the number of predictors considered at each split is approximately equal to the square root of the total number of predictors (19 out of the 369 for the ALS data).</p></li>
</ul>
</section>
<section id="section-1" class="level2">
<h2 class="anchored" data-anchor-id="section-1"></h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="un_D_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="900"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="boosting" class="level2">
<h2 class="anchored" data-anchor-id="boosting">Boosting</h2>
<ul>
<li><p>Recall that bagging involves creating multiple copies of the original training data set using the bootstrap, fitting a separate decision tree to each copy, and then combining all of the trees in order to create a single predictive model.</p></li>
<li><p>Notably, each tree is built on a bootstrap data set, independent of the other trees.</p></li>
<li><p>Boosting works in a similar way, except that the trees are grown <span class="blue">sequentially</span>: each tree is grown using information from previously grown trees.</p></li>
</ul>
</section>
<section id="boosting-algorithm-for-regression-trees" class="level2">
<h2 class="anchored" data-anchor-id="boosting-algorithm-for-regression-trees">Boosting algorithm for regression trees</h2>
<ol type="1">
<li><p>Set <span class="math inline">\hat f(x) = 0</span> and <span class="math inline">r_i = y_i</span> for all <span class="math inline">i</span> iin the training set</p></li>
<li><p>For <span class="math inline">b=1,\ldot,B</span>, repeat:</p>
<p>2.1 Ft a tree <span class="math inline">\hat f^b</span> with <span class="math inline">d</span> splits (<span class="math inline">d+1</span> terminal nodes) to the training data <span class="math inline">(X,r)</span></p>
<p>2.2 Update <span class="math inline">\hat f</span> by adding in a shrunken version of the new tree:</p>
<p><span class="math display">\hat f(x) \leftarrow \hat f(x) + \lambda \hat f^b(x)</span> 2.3 Update the residuals</p>
<p><span class="math display">r_i \leftarrow r_i - \lambda \hat f^b(x_i)</span></p></li>
<li><p>Output the boosted model,</p></li>
</ol>
<p><span class="math display">\hat f(x) = \sum_{b=1}^{B} \lambda \hat f^b(x)</span></p>
</section>
<section id="toy-example-b50-d1-lambda-0.01" class="level2">
<h2 class="anchored" data-anchor-id="toy-example-b50-d1-lambda-0.01">Toy Example (<span class="math inline">B=50, d=1, \lambda =0.01</span>)</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/boosting_animation.gif" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</section>
<section id="what-is-the-idea-behind-this-procedure" class="level2">
<h2 class="anchored" data-anchor-id="what-is-the-idea-behind-this-procedure">What is the idea behind this procedure?</h2>
<p>Unlike fitting a single large decision tree to the data, which amounts to <span class="blue">fitting the data hard</span> and potentially overfitting, the boosting approach instead <span class="blue">learns slowly</span>.</p>
<ul>
<li><p>Given the current model, we fit a decision tree to the residuals from the model. We then add this new decision tree into the fitted function in order to update the residuals.</p></li>
<li><p>Each of these trees can be rather small, with just a few terminal nodes, determined by the parameter d in the algorithm.</p></li>
<li><p>By fitting small trees to the residuals, we slowly improve <span class="math inline">\hat f</span> in areas where it does not perform well. The shrinkage parameter <span class="math inline">\lambda</span> slows the process down even further, allowing more and different shaped trees to attack the residuals.</p></li>
</ul>
</section>
<section id="tuning-parameters-for-boosting" class="level2">
<h2 class="anchored" data-anchor-id="tuning-parameters-for-boosting">Tuning parameters for boosting</h2>
<ol type="1">
<li><p>The <span class="orange">number of trees</span> <span class="math inline">B</span>. Unlike bagging and random forests, boosting can overfit if <span class="math inline">B</span> is too large, although this overfitting tends to occur slowly if at all. We use cross-validation to select <span class="math inline">B</span>.</p></li>
<li><p>The <span class="orange">shrinkage parameter</span> <span class="math inline">\lambda</span>, a small positive number. This controls the rate at which boosting learns. Typical values are 0.01 or 0.001, and the right choice can depend on the problem. Very small <span class="math inline">\lambda</span> can require using a very large value of <span class="math inline">B</span> in order to achieve good performance.</p></li>
<li><p>The <span class="orange">number of splits</span> <span class="math inline">d</span> in each tree, which controls the complexity of the boosted ensemble. Often <span class="math inline">d= 1</span> works well, in which case each tree is a <span class="blue">stump</span>, consisting of a single split and resulting in an additive model. More generally <span class="math inline">d</span> is the <span class="blue">interaction depth</span>, and controls the interaction order of the boosted model, since <span class="math inline">d</span> splits can involve at most <span class="math inline">d</span> variables.</p></li>
</ol>
</section>
<section id="casi-figure-17.6" class="level2">
<h2 class="anchored" data-anchor-id="casi-figure-17.6">CASI, Figure 17.6</h2>
<p>Efron and Hastie, 2016, Computer Age Statistical Inference, Cambridge University Press.</p>
<p><img src="img/Fig17_6.png" class="img-fluid" style="width:80.0%"></p>
<p><strong>Figure 17.6.</strong> Test performance of a boosted regression-tree model fit to the ALS training data, with <span class="math inline">n = 1197</span> and <span class="math inline">p = 369</span>. Shown is the mean squared error (MSE) on the 625 designated test observations as a function of the number of trees. The model uses tree depth <span class="math inline">d = 4</span> and shrinkage parameter <span class="math inline">\lambda = 0.02</span>.</p>
<p>Boosting achieves a lower test MSE than a random forest. However, as the number of trees <span class="math inline">B</span> becomes large, the test error for boosting begins to increase, indicating overfitting. In contrast, the random forest does not exhibit overfitting. The dotted blue horizontal line represents the best performance of a linear model fitted using the lasso. Note that the differences are less dramatic than they appear, since the vertical axis does not extend to zero.</p>
</section>
<section id="casi-figure-17.8" class="level2">
<h2 class="anchored" data-anchor-id="casi-figure-17.8">CASI Figure 17.8</h2>
<p><img src="img/Fig17_8.png" class="img-fluid" style="width:80.0%"></p>
<p><strong>Figure 17.8.</strong> ALS test error for boosted models with different tree depths <span class="math inline">d</span>, all using the same shrinkage parameter <span class="math inline">\lambda 00.02</span>.</p>
<p>The model with <span class="math inline">d = 1</span> performs worse than the others, while ( d = 4 ) appears to perform best overall. For <span class="math inline">d = 7</span>, overfitting begins at around 200 trees; for <span class="math inline">d = 4</span>, it begins around 300 trees. The remaining models show no clear evidence of overfitting even up to 500 trees.</p>
</section>
<section id="casi-figure-17.6-1" class="level2">
<h2 class="anchored" data-anchor-id="casi-figure-17.6-1">CASI Figure 17.6</h2>
<p><img src="img/Fig17_10.png" class="img-fluid" style="width:80.0%"></p>
<p><strong>Figure 17.10.</strong> Boosted models with depth <span class="math inline">d = 3</span> and different shrinkage parameters, fitted to a subset of the ALS data. Solid curves show validation error, and dashed curves show training error. Red corresponds to <span class="math inline">\lambda = 0.5</span>, and blue to <span class="math inline">\lambda = 0.02</span>.</p>
<p>With <span class="math inline">\lambda = 0.5</span>, the training error decreases rapidly as the number of trees increases, but the validation error rises quickly after an initial decline, indicating overfitting. With <span class="math inline">\lambda = 0.02</span> (25 times smaller), both training and validation errors decrease more gradually. However, the validation error reaches a lower minimum (indicated by the horizontal dotted line) than in the <span class="math inline">\lambda = 0.5</span> case. In this setting, slower learning leads to better generalization.</p>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<ul>
<li><p>Decision trees are simple and interpretable models for regression</p></li>
<li><p>However they are often not competitive with other methods in terms of prediction accuracy</p></li>
<li><p>Bagging, random forests and boosting are good methods for improving the prediction accuracy of trees. They work by growing many trees on the training data and then combining the predictions of the resulting ensemble of trees.</p></li>
<li><p>The latter two methods— random forests and boosting— are among the state-of-the-art methods for supervised learning. However their results can be diﬃcult to interpret.</p></li>
</ul>
</section>
<section id="required-readings-from-the-textbook-and-course-materials" class="level2">
<h2 class="anchored" data-anchor-id="required-readings-from-the-textbook-and-course-materials">Required readings from the textbook and course materials</h2>
<ul>
<li><strong>Chapter 8: Tree-Based Methods</strong>
<ul>
<li>8.1 The Basics of Decision Trees
<ul>
<li>8.1.1 Regression Trees</li>
<li>8.1.3 Trees Versus Linear Models</li>
<li>8.1.4 Advantages and Disadvantages of Trees</li>
</ul></li>
<li>8.2 Bagging, Random Forests, Boosting
<ul>
<li>8.2.1 Bagging</li>
<li>8.2.2 Random Forests</li>
<li>8.2.3 Boosting</li>
<li>8.2.5 Summary of Tree Ensemble Methods . . . . . . . . 351</li>
</ul></li>
</ul></li>
</ul>
<p><a href="https://www.youtube.com/playlist?list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e">Video SL 8.1 Tree-Based Methods - 14:38</a><br>
<a href="https://www.youtube.com/playlist?list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e">Video SL 8.2 More Details on Trees - 11:46</a><br>
<a href="https://www.youtube.com/playlist?list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e">Video SL 8.4 Bagging - 13:46</a><br>
<a href="https://www.youtube.com/playlist?list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e">Video SL 8.5 Boosting - 12:03</a></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="un_D_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>