---
title: "	Exercises A"
subtitle: "Bachelor’s Degree Programme in Philosophy, International and Economic Studies, Ca' Foscari University of Venice."
author: "Aldo Solari"
institute: "Department of Economics, Ca' Foscari University of Venice"
lang: en
page-layout: full
execute:
  cache: false
format:
  html:
    html-math-method: katex
    echo: true
    callout-appearance: minimal
    theme: [simplex, template.css]
    toc: true
    toc-title: Table of contents
    embed-resources: false
    code-line-numbers: true
    smooth-scroll: true
    fig-dpi: 250
editor: 
  markdown: 
    wrap: 72
editor_options: 
  chunk_output_type: console
---


# [Homepage](../index.html)

## Exercises A


### Conceptual


#### Chapter 2 Exercise 2.

Explain whether each scenario is a classification or regression problem, and indicate whether we are most interested in inference or prediction. Finally, provide $n$ and $p$.

(a) We collect a set of data on the top 500 firms in the US. For each firm we record profit, number of employees, industry and the CEO salary. We are interested in understanding which factors affect CEO salary.

(b) We are considering launching a new product and wish to know whether it will be a success or a failure. We collect data on 20 similar products that were previously launched. For each product we have recorded whether it was a success or failure, price charged for the product, marketing budget, competition price, and ten other variables.

(c) We are interested in predicting the % change in the USD/Euro exchange rate in relation to the weekly changes in the world stock markets. Hence we collect weekly data for all of 2012. For each week we record the % change in the USD/Euro, the % change in the US market, the % change in the British market, and the % change in the German market.






### Applied

#### Chapter 2 Exercise 8.

This exercise relates to the `College` data set, which can be found in the file `College.csv`. It contains a number of variables for 777 different universities and colleges in the US. The variables are

- `Private` : Public/private indicator  
- `Apps` : Number of applications received  
- `Accept` : Number of applicants accepted  
- `Enroll` : Number of new students enrolled  
- `Top10perc` : New students from top 10% of high school class  
- `Top25perc` : New students from top 25% of high school class  
- `F.Undergrad` : Number of full-time undergraduates  
- `P.Undergrad` : Number of part-time undergraduates  
- `Outstate` : Out-of-state tuition  
- `Room.Board` : Room and board costs  
- `Books` : Estimated book costs  
- `Personal` : Estimated personal spending  
- `PhD` : Percent of faculty with Ph.D.’s  
- `Terminal` : Percent of faculty with terminal degree  
- `S.F.Ratio` : Student/faculty ratio  
- `perc.alumni` : Percent of alumni who donate  
- `Expend` : Instructional expenditure per student  
- `Grad.Rate` : Graduation rate  


Before reading the data into R, it can be viewed in Excel or a text editor.

(a) Use the `read.csv()` function to read the data into R. Call the loaded data college. Make sure that you have the directory set to the correct location for the data.

(b) 
