---
title: "Exercises Unit B - Conceptual"
subtitle: "Bachelor’s Degree Programme in Philosophy, International and Economic Studies, Ca' Foscari University of Venice."
author: "Aldo Solari"
institute: "Department of Economics, Ca' Foscari University of Venice"
lang: en
page-layout: full
execute:
  cache: false
format:
  html:
    html-math-method: katex
    echo: true
    callout-appearance: minimal
    theme: [simplex, template.css]
    toc: true
    toc-title: Table of contents
    embed-resources: false
    code-line-numbers: true
    smooth-scroll: true
    fig-dpi: 250
editor: 
  markdown: 
    wrap: 72
editor_options: 
  chunk_output_type: console
---


### [Homepage](../index.html)

#### Chapter 3 Exercise 3.

Suppose we have a data set with five predictors:

- $X_1 = \text{GPA}$
- $X_2 = \text{IQ}$
- $X_3 = \text{Level}$ (1 for College and 0 for High School)
- $X_4 = \text{GPA} \times \text{IQ}$
- $X_5 = \text{GPA} \times \text{Level}$

The response is starting salary after graduation (in thousands of dollars).  
Suppose we use least squares to fit the model, and obtain:

$$
\hat{\beta}_0 = 50,\quad
\hat{\beta}_1 = 20,\quad
\hat{\beta}_2 = 0.07,\quad
\hat{\beta}_3 = 35,\quad
\hat{\beta}_4 = 0.01,\quad
\hat{\beta}_5 = -10
$$


(a) Which answer is correct, and why?

    i. For a fixed value of IQ and GPA, high school graduates earn more, on average, than college graduates.  

    ii. For a fixed value of IQ and GPA, college graduates earn more, on average, than high school graduates.  

    iii. For a fixed value of IQ and GPA, high school graduates earn more, on average, than college graduates provided that the GPA is high enough.  

    iv. For a fixed value of IQ and GPA, college graduates earn more, on average, than high school graduates provided that the GPA is high enough.  

(b) Predict the salary of a college graduate with IQ of 110 and a GPA of 4.0.  

(c) True or false: Since the coefficient for the GPA/IQ interaction term is very small, there is very little evidence of an interaction effect. Justify your answer.

